import mysql from 'mysql2/promise';

const DB = { host:'songtute.c8spusdhenpr.ap-southeast-1.rds.amazonaws.com', user:'admin', password:'jFUnRCumnerGsGaPT5pR', database:'songtute' };
const SQL = `INSERT INTO quizzes (lessonId,exerciseNumber,questionType,questionText,optionsJson,correctAnswerJson,difficultyLevel,explanation,points,sortOrder,isActive,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,1,NOW(),NOW())`;

type Q = { lessonId:number; ex:number; type:string; text:string; opts?:object; ans:unknown; diff:string; sort:number; expl?:string };

const A = (lessonId:number, ex:number, type:string, text:string, opts:object|null, ans:unknown, diff:string, sort:number, expl?:string): Q =>
  ({ lessonId, ex, type, text, ...(opts?{opts}:{}), ans, diff, sort, ...(expl?{expl}:{}) });

const QUIZZES: Q[] = [
  // ── 123: Các số 0,1,2,3,4,5 ──
  ...([
    A(123,1,'single_choice','Số nào đứng sau số 3?',[{key:'A',text:'2'},{key:'B',text:'4'},{key:'C',text:'5'}],'B','easy',1),
    A(123,1,'single_choice','Có mấy ngôi sao: ★★★?',[{key:'A',text:'2'},{key:'B',text:'3'},{key:'C',text:'4'}],'B','easy',2),
    A(123,1,'single_choice','Số 0 đứng trước số nào?',[{key:'A',text:'0'},{key:'B',text:'1'},{key:'C',text:'2'}],'B','easy',3),
    A(123,1,'true_false','Số 5 lớn hơn số 4. Đúng hay sai?',null,true,'easy',4),
    A(123,1,'true_false','Số 0 là số nhỏ nhất trong các số 0,1,2,3,4,5. Đúng hay sai?',null,true,'easy',5),
    A(123,1,'fill_blank','[b1] + 1 = 4',[{key:'b1',text:''}],{b1:'3'},'easy',6),
    A(123,1,'fill_blank','5 - [b1] = 3',[{key:'b1',text:''}],{b1:'2'},'easy',7),
    A(123,1,'counting','Đếm số quả táo: 🍎🍎🍎🍎',[{key:'d1',text:'🍎'},{key:'d2',text:'🍎'},{key:'d3',text:'🍎'},{key:'d4',text:'🍎'}],'4','easy',8),
    A(123,1,'sorting','Sắp xếp tăng dần',[{key:'1',text:'3'},{key:'2',text:'1'},{key:'3',text:'5'},{key:'4',text:'0'}],['4','2','1','3'],'easy',9),
    A(123,1,'cross_out','Gạch bỏ số không thuộc dãy 0-5',[{key:'A',text:'3'},{key:'B',text:'7'},{key:'C',text:'5'},{key:'D',text:'9'}],['B','D'],'easy',10),
    A(123,2,'single_choice','Số liền trước của 4 là?',[{key:'A',text:'2'},{key:'B',text:'3'},{key:'C',text:'5'}],'B','medium',1),
    A(123,2,'single_choice','2 + 3 = ?',[{key:'A',text:'4'},{key:'B',text:'5'},{key:'C',text:'6'}],'B','medium',2),
    A(123,2,'multiple_choice','Số nào nhỏ hơn 3?',[{key:'A',text:'0'},{key:'B',text:'1'},{key:'C',text:'3'},{key:'D',text:'4'}],['A','B'],'medium',3),
    A(123,2,'multiple_choice','Số nào lớn hơn 2?',[{key:'A',text:'1'},{key:'B',text:'3'},{key:'C',text:'0'},{key:'D',text:'5'}],['B','D'],'medium',4),
    A(123,2,'matching','Nối số với số chấm',[{key:'A',text:'2'},{key:'B',text:'4'},{key:'C',text:'1'}],{A:'••',B:'••••',C:'•'},'medium',5),
    A(123,2,'matching','Nối phép tính với kết quả',[{key:'A',text:'1+2'},{key:'B',text:'3+1'},{key:'C',text:'0+5'}],{A:'3',B:'4',C:'5'},'medium',6),
    A(123,2,'drag_drop','Sắp xếp: 5,2,4,1',[{key:'1',text:'5'},{key:'2',text:'2'},{key:'3',text:'4'},{key:'4',text:'1'}],['4','2','3','1'],'medium',7),
    A(123,2,'table_fill','Điền vào bảng',[{key:'headers',text:'Số|Số liền trước|Số liền sau'},{key:'r1',text:'3|_r1c1|_r1c2'}],{r1c1:'2',r1c2:'4'},'medium',8),
    A(123,2,'number_line','Điền số còn thiếu trên tia số (0-5)',[{key:'min',text:'0'},{key:'max',text:'5'},{key:'step',text:'1'},{key:'marks',text:'0|1|2|3|4|5'},{key:'hidden',text:'3'}],['3'],'medium',9),
    A(123,2,'puzzle','Ghép ô',[{key:'slot_1',text:'? + 2 = 5'},{key:'token_3',text:'3'},{key:'token_2',text:'2'}],{slot_1:'token_3'},'medium',10),
    A(123,3,'fill_blank','[b1] + 2 = 5',[{key:'b1',text:''}],{b1:'3'},'hard',1),
    A(123,3,'fill_blank','4 - [b1] = 1',[{key:'b1',text:''}],{b1:'3'},'hard',2),
    A(123,3,'puzzle','Ghép ô',[{key:'slot_1',text:'3 + ? = 5'},{key:'slot_2',text:'? + 1 = 4'},{key:'token_2',text:'2'},{key:'token_3',text:'3'}],{slot_1:'token_2',slot_2:'token_3'},'hard',3),
    A(123,3,'puzzle','Ghép số với hình',[{key:'slot_1',text:'4 chấm = ?'},{key:'token_4',text:'4'},{key:'token_5',text:'5'}],{slot_1:'token_4'},'hard',4),
    A(123,3,'game','Ghép cặp bằng nhau',[{key:'c1',text:'1+2',pair:'ba'},{key:'c2',text:'0+3',pair:'ba'},{key:'c3',text:'2+2',pair:'bon'},{key:'c4',text:'1+3',pair:'bon'},{key:'c5',text:'1+4',pair:'nam'},{key:'c6',text:'0+5',pair:'nam'}],{},'hard',5),
    A(123,3,'sorting','Sắp xếp giảm dần: 1,4,2,5,0',[{key:'1',text:'1'},{key:'2',text:'4'},{key:'3',text:'2'},{key:'4',text:'5'},{key:'5',text:'0'}],['4','2','3','1','5'],'hard',6),
    A(123,3,'matching','Nối số với tên gọi',[{key:'A',text:'0'},{key:'B',text:'3'},{key:'C',text:'5'}],{A:'không',B:'ba',C:'năm'},'hard',7),
    A(123,3,'multiple_choice','Số nào bằng 2+1?',[{key:'A',text:'2'},{key:'B',text:'3'},{key:'C',text:'4'},{key:'D',text:'5'}],['B'],'hard',8),
    A(123,3,'multiple_choice','Phép tính nào có kết quả là 4?',[{key:'A',text:'2+2'},{key:'B',text:'3+1'},{key:'C',text:'1+2'},{key:'D',text:'0+5'}],['A','B'],'hard',9),
    A(123,3,'drag_drop','Sắp xếp tăng dần: 3,0,5,2,1',[{key:'1',text:'3'},{key:'2',text:'0'},{key:'3',text:'5'},{key:'4',text:'2'},{key:'5',text:'1'}],['2','5','4','1','3'],'hard',10),
  ]),
  // ── 124: Các số 6,7,8,9,10 ──
  ...([
    A(124,1,'single_choice','Số nào đứng sau số 8?',[{key:'A',text:'7'},{key:'B',text:'9'},{key:'C',text:'10'}],'B','easy',1),
    A(124,1,'single_choice','Có mấy ngôi sao: ★★★★★★★?',[{key:'A',text:'6'},{key:'B',text:'7'},{key:'C',text:'8'}],'B','easy',2),
    A(124,1,'single_choice','Số liền trước 10 là?',[{key:'A',text:'8'},{key:'B',text:'9'},{key:'C',text:'10'}],'B','easy',3),
    A(124,1,'true_false','Số 10 lớn hơn số 9. Đúng hay sai?',null,true,'easy',4),
    A(124,1,'true_false','Số 7 đứng trước số 8. Đúng hay sai?',null,true,'easy',5),
    A(124,1,'fill_blank','6 + [b1] = 10',[{key:'b1',text:''}],{b1:'4'},'easy',6),
    A(124,1,'fill_blank','[b1] + 3 = 9',[{key:'b1',text:''}],{b1:'6'},'easy',7),
    A(124,1,'counting','Đếm số bông hoa: 🌸🌸🌸🌸🌸🌸🌸🌸',[{key:'d1',text:'🌸'},{key:'d2',text:'🌸'},{key:'d3',text:'🌸'},{key:'d4',text:'🌸'},{key:'d5',text:'🌸'},{key:'d6',text:'🌸'},{key:'d7',text:'🌸'},{key:'d8',text:'🌸'}],'8','easy',8),
    A(124,1,'sorting','Sắp xếp tăng dần',[{key:'1',text:'8'},{key:'2',text:'6'},{key:'3',text:'10'},{key:'4',text:'7'}],['2','4','1','3'],'easy',9),
    A(124,1,'cross_out','Gạch bỏ số không thuộc 6-10',[{key:'A',text:'8'},{key:'B',text:'4'},{key:'C',text:'9'},{key:'D',text:'3'}],['B','D'],'easy',10),
    A(124,2,'single_choice','6 + 3 = ?',[{key:'A',text:'8'},{key:'B',text:'9'},{key:'C',text:'10'}],'B','medium',1),
    A(124,2,'single_choice','10 - 2 = ?',[{key:'A',text:'7'},{key:'B',text:'8'},{key:'C',text:'9'}],'B','medium',2),
    A(124,2,'multiple_choice','Số nào lớn hơn 7?',[{key:'A',text:'6'},{key:'B',text:'8'},{key:'C',text:'5'},{key:'D',text:'9'}],['B','D'],'medium',3),
    A(124,2,'multiple_choice','Số nào nhỏ hơn 9?',[{key:'A',text:'10'},{key:'B',text:'7'},{key:'C',text:'8'},{key:'D',text:'6'}],['B','C','D'],'medium',4),
    A(124,2,'matching','Nối phép tính với kết quả',[{key:'A',text:'5+3'},{key:'B',text:'4+4'},{key:'C',text:'3+7'}],{A:'8',B:'8',C:'10'},'medium',5),
    A(124,2,'matching','Nối số với tên',[{key:'A',text:'6'},{key:'B',text:'9'},{key:'C',text:'10'}],{A:'sáu',B:'chín',C:'mười'},'medium',6),
    A(124,2,'drag_drop','Sắp xếp: 10,6,8,7',[{key:'1',text:'10'},{key:'2',text:'6'},{key:'3',text:'8'},{key:'4',text:'7'}],['2','4','3','1'],'medium',7),
    A(124,2,'table_fill','Điền bảng',[{key:'headers',text:'Số|Liền trước|Liền sau'},{key:'r1',text:'8|_r1c1|_r1c2'},{key:'r2',text:'10|_r2c1|_r2c2'}],{r1c1:'7',r1c2:'9',r2c1:'9',r2c2:'11'},'medium',8),
    A(124,2,'number_line','Điền số thiếu (6-10)',[{key:'min',text:'6'},{key:'max',text:'10'},{key:'step',text:'1'},{key:'marks',text:'6|7|8|9|10'},{key:'hidden',text:'8'}],['8'],'medium',9),
    A(124,2,'puzzle','Ghép ô',[{key:'slot_1',text:'? + 4 = 10'},{key:'token_6',text:'6'},{key:'token_4',text:'4'}],{slot_1:'token_6'},'medium',10),
    A(124,3,'fill_blank','[b1] + 4 = 10',[{key:'b1',text:''}],{b1:'6'},'hard',1),
    A(124,3,'fill_blank','9 - [b1] = 3',[{key:'b1',text:''}],{b1:'6'},'hard',2),
    A(124,3,'puzzle','Ghép ô',[{key:'slot_1',text:'7 + ? = 10'},{key:'slot_2',text:'? + 2 = 8'},{key:'token_3',text:'3'},{key:'token_6',text:'6'}],{slot_1:'token_3',slot_2:'token_6'},'hard',3),
    A(124,3,'puzzle','Ghép cặp cộng = 10',[{key:'slot_1',text:'6 + ?'},{key:'slot_2',text:'8 + ?'},{key:'token_4',text:'4'},{key:'token_2',text:'2'}],{slot_1:'token_4',slot_2:'token_2'},'hard',4),
    A(124,3,'game','Ghép phép tính với kết quả',[{key:'c1',text:'3+4',pair:'bay'},{key:'c2',text:'1+6',pair:'bay'},{key:'c3',text:'4+4',pair:'tam'},{key:'c4',text:'10-2',pair:'tam'},{key:'c5',text:'5+4',pair:'chin'},{key:'c6',text:'10-1',pair:'chin'}],{},'hard',5),
    A(124,3,'sorting','Sắp xếp giảm dần: 6,10,7,9,8',[{key:'1',text:'6'},{key:'2',text:'10'},{key:'3',text:'7'},{key:'4',text:'9'},{key:'5',text:'8'}],['2','4','5','3','1'],'hard',6),
    A(124,3,'matching','Nối',[{key:'A',text:'10-3'},{key:'B',text:'5+2'},{key:'C',text:'8+1'}],{A:'7',B:'7',C:'9'},'hard',7),
    A(124,3,'multiple_choice','Số nào bằng 10-3?',[{key:'A',text:'6'},{key:'B',text:'7'},{key:'C',text:'8'},{key:'D',text:'9'}],['B'],'hard',8),
    A(124,3,'multiple_choice','Tổng nào bằng 10?',[{key:'A',text:'6+4'},{key:'B',text:'7+3'},{key:'C',text:'5+5'},{key:'D',text:'6+3'}],['A','B','C'],'hard',9),
    A(124,3,'drag_drop','Sắp xếp tăng dần',[{key:'1',text:'9'},{key:'2',text:'6'},{key:'3',text:'7'},{key:'4',text:'10'},{key:'5',text:'8'}],['2','3','5','1','4'],'hard',10),
  ]),
  // ── 125: Nhiều hơn, ít hơn, bằng nhau ──
  ...([
    A(125,1,'single_choice','Nhóm A có 5 quả, nhóm B có 3 quả. Nhóm nào nhiều hơn?',[{key:'A',text:'Nhóm A'},{key:'B',text:'Nhóm B'},{key:'C',text:'Bằng nhau'}],'A','easy',1),
    A(125,1,'single_choice','4 con mèo và 4 con chó. Chúng như thế nào?',[{key:'A',text:'Mèo nhiều hơn'},{key:'B',text:'Chó nhiều hơn'},{key:'C',text:'Bằng nhau'}],'C','easy',2),
    A(125,1,'single_choice','2 < 5. Vậy 2 ... 5?',[{key:'A',text:'nhiều hơn'},{key:'B',text:'ít hơn'},{key:'C',text:'bằng'}],'B','easy',3),
    A(125,1,'true_false','3 ít hơn 5. Đúng hay sai?',null,true,'easy',4),
    A(125,1,'true_false','6 bằng 6. Đúng hay sai?',null,true,'easy',5),
    A(125,1,'fill_blank','4 nhiều hơn 2 là [b1]',[{key:'b1',text:''}],{b1:'2'},'easy',6),
    A(125,1,'fill_blank','7 ít hơn 10 là [b1]',[{key:'b1',text:''}],{b1:'3'},'easy',7),
    A(125,1,'counting','Đếm: 🐟🐟🐟🐟🐟',[{key:'d1',text:'🐟'},{key:'d2',text:'🐟'},{key:'d3',text:'🐟'},{key:'d4',text:'🐟'},{key:'d5',text:'🐟'}],'5','easy',8),
    A(125,1,'sorting','Sắp xếp từ ít đến nhiều: 7,3,5,9',[{key:'1',text:'7'},{key:'2',text:'3'},{key:'3',text:'5'},{key:'4',text:'9'}],['2','3','1','4'],'easy',9),
    A(125,1,'cross_out','Gạch số không ít hơn 5 (giữ số < 5)',[{key:'A',text:'3'},{key:'B',text:'6'},{key:'C',text:'2'},{key:'D',text:'8'}],['B','D'],'easy',10),
    A(125,2,'single_choice','An có 8 bi, Bình có 5 bi. An hơn Bình mấy bi?',[{key:'A',text:'2'},{key:'B',text:'3'},{key:'C',text:'4'}],'B','medium',1),
    A(125,2,'single_choice','Lớp A 9 bạn, lớp B 9 bạn. So sánh?',[{key:'A',text:'Lớp A nhiều hơn'},{key:'B',text:'Bằng nhau'},{key:'C',text:'Lớp B nhiều hơn'}],'B','medium',2),
    A(125,2,'multiple_choice','Số nào ít hơn 6?',[{key:'A',text:'4'},{key:'B',text:'7'},{key:'C',text:'3'},{key:'D',text:'9'}],['A','C'],'medium',3),
    A(125,2,'multiple_choice','Nhóm nào bằng nhau?',[{key:'A',text:'3 và 3'},{key:'B',text:'5 và 5'},{key:'C',text:'4 và 5'},{key:'D',text:'2 và 3'}],['A','B'],'medium',4),
    A(125,2,'matching','Nối',[{key:'A',text:'8 và 5'},{key:'B',text:'4 và 4'},{key:'C',text:'3 và 7'}],{A:'nhiều hơn',B:'bằng nhau',C:'ít hơn'},'medium',5),
    A(125,2,'matching','Nối phép so sánh',[{key:'A',text:'5 _ 8'},{key:'B',text:'9 _ 9'},{key:'C',text:'7 _ 4'}],{A:'<',B:'=',C:'>'},'medium',6),
    A(125,2,'drag_drop','Sắp xếp: 8,3,10,6,1',[{key:'1',text:'8'},{key:'2',text:'3'},{key:'3',text:'10'},{key:'4',text:'6'},{key:'5',text:'1'}],['5','2','4','1','3'],'medium',7),
    A(125,2,'table_fill','Điền bảng',[{key:'headers',text:'Nhóm A|Nhóm B|Nhiều hơn'},{key:'r1',text:'7|5|_r1c1'}],{r1c1:'A'},'medium',8),
    A(125,2,'number_line','Số nào thiếu',[{key:'min',text:'0'},{key:'max',text:'10'},{key:'step',text:'1'},{key:'marks',text:'0|2|4|6|8|10'},{key:'hidden',text:'6'}],['6'],'medium',9),
    A(125,2,'puzzle','Ghép ô',[{key:'slot_1',text:'5 _ 7 (nhiều hay ít?)'},{key:'token_it',text:'ít hơn'},{key:'token_nhieu',text:'nhiều hơn'}],{slot_1:'token_it'},'medium',10),
    A(125,3,'fill_blank','9 hơn 4 là [b1]',[{key:'b1',text:''}],{b1:'5'},'hard',1),
    A(125,3,'fill_blank','[b1] ít hơn 8 là 3',[{key:'b1',text:''}],{b1:'5'},'hard',2),
    A(125,3,'puzzle','Ghép',[{key:'slot_1',text:'6 _ 4'},{key:'slot_2',text:'3 _ 3'},{key:'token_gt',text:'>'},{key:'token_eq',text:'='}],{slot_1:'token_gt',slot_2:'token_eq'},'hard',3),
    A(125,3,'puzzle','Điền dấu',[{key:'slot_1',text:'10 _ 9'},{key:'slot_2',text:'5 _ 7'},{key:'token_gt',text:'>'},{key:'token_lt',text:'<'}],{slot_1:'token_gt',slot_2:'token_lt'},'hard',4),
    A(125,3,'game','Ghép cặp',[{key:'c1',text:'8>5',pair:'dung'},{key:'c2',text:'3<7',pair:'dung'},{key:'c3',text:'9>6',pair:'dung'},{key:'c4',text:'4=4',pair:'bang'},{key:'c5',text:'6=6',pair:'bang'},{key:'c6',text:'2=2',pair:'bang'}],{},'hard',5),
    A(125,3,'sorting','Sắp xếp giảm dần: 4,9,2,7,5',[{key:'1',text:'4'},{key:'2',text:'9'},{key:'3',text:'2'},{key:'4',text:'7'},{key:'5',text:'5'}],['2','4','5','1','3'],'hard',6),
    A(125,3,'matching','Nối',[{key:'A',text:'10-2'},{key:'B',text:'6+2'},{key:'C',text:'5+3'}],{A:'8',B:'8',C:'8'},'hard',7),
    A(125,3,'multiple_choice','Số nào lớn hơn 6 và nhỏ hơn 9?',[{key:'A',text:'5'},{key:'B',text:'7'},{key:'C',text:'8'},{key:'D',text:'9'}],['B','C'],'hard',8),
    A(125,3,'multiple_choice','Phép so sánh nào đúng?',[{key:'A',text:'3>5'},{key:'B',text:'7>4'},{key:'C',text:'8>9'},{key:'D',text:'6<10'}],['B','D'],'hard',9),
    A(125,3,'drag_drop','Sắp xếp theo thứ tự: ít nhất đến nhiều nhất',[{key:'1',text:'5'},{key:'2',text:'1'},{key:'3',text:'8'},{key:'4',text:'3'}],['2','4','1','3'],'hard',10),
  ]),
  // ── 126: So sánh số ──
  ...([
    A(126,1,'single_choice','3 ... 5?',[{key:'A',text:'>'},{key:'B',text:'<'},{key:'C',text:'='}],'B','easy',1),
    A(126,1,'single_choice','7 ... 4?',[{key:'A',text:'>'},{key:'B',text:'<'},{key:'C',text:'='}],'A','easy',2),
    A(126,1,'single_choice','6 ... 6?',[{key:'A',text:'>'},{key:'B',text:'<'},{key:'C',text:'='}],'C','easy',3),
    A(126,1,'true_false','4 < 7 là đúng. Đúng hay sai?',null,true,'easy',4),
    A(126,1,'true_false','9 > 10 là đúng. Đúng hay sai?',null,false,'easy',5),
    A(126,1,'fill_blank','5 [b1] 3 (điền dấu >, <, =)',[{key:'b1',text:''}],{b1:'>'},'easy',6),
    A(126,1,'fill_blank','8 [b1] 8',[{key:'b1',text:''}],{b1:'='},'easy',7),
    A(126,1,'counting','Đếm: 🐰🐰🐰🐰🐰🐰',[{key:'d1',text:'🐰'},{key:'d2',text:'🐰'},{key:'d3',text:'🐰'},{key:'d4',text:'🐰'},{key:'d5',text:'🐰'},{key:'d6',text:'🐰'}],'6','easy',8),
    A(126,1,'sorting','Sắp xếp tăng dần: 4,9,2,7',[{key:'1',text:'4'},{key:'2',text:'9'},{key:'3',text:'2'},{key:'4',text:'7'}],['3','1','4','2'],'easy',9),
    A(126,1,'cross_out','Gạch bỏ phép so sánh sai',[{key:'A',text:'3>1'},{key:'B',text:'5<3'},{key:'C',text:'8>6'},{key:'D',text:'2>4'}],['B','D'],'easy',10),
    A(126,2,'single_choice','Số nào lớn nhất: 3,7,5?',[{key:'A',text:'3'},{key:'B',text:'5'},{key:'C',text:'7'}],'C','medium',1),
    A(126,2,'single_choice','Số nhỏ nhất trong: 6,2,9?',[{key:'A',text:'2'},{key:'B',text:'6'},{key:'C',text:'9'}],'A','medium',2),
    A(126,2,'multiple_choice','Dấu nào điền đúng vào 5 _ 8?',[{key:'A',text:'>'},{key:'B',text:'<'},{key:'C',text:'='},{key:'D',text:'≠'}],['B'],'medium',3),
    A(126,2,'multiple_choice','Phép so sánh nào đúng?',[{key:'A',text:'10>9'},{key:'B',text:'7>8'},{key:'C',text:'4<6'},{key:'D',text:'5=5'}],['A','C','D'],'medium',4),
    A(126,2,'matching','Nối',[{key:'A',text:'2 _ 5'},{key:'B',text:'8 _ 3'},{key:'C',text:'6 _ 6'}],{A:'<',B:'>',C:'='},'medium',5),
    A(126,2,'matching','Nối số với vị trí tương ứng',[{key:'A',text:'lớn nhất trong 3,5,8'},{key:'B',text:'nhỏ nhất trong 2,6,4'},{key:'C',text:'ở giữa 5,7,9'}],{A:'8',B:'2',C:'7'},'medium',6),
    A(126,2,'drag_drop','Sắp xếp tăng dần: 6,1,8,3,5',[{key:'1',text:'6'},{key:'2',text:'1'},{key:'3',text:'8'},{key:'4',text:'3'},{key:'5',text:'5'}],['2','4','5','1','3'],'medium',7),
    A(126,2,'table_fill','Điền dấu',[{key:'headers',text:'Số 1|Dấu|Số 2'},{key:'r1',text:'7|_r1c1|5'},{key:'r2',text:'4|_r2c1|9'}],{r1c1:'>',r2c1:'<'},'medium',8),
    A(126,2,'number_line','Số thiếu',[{key:'min',text:'0'},{key:'max',text:'10'},{key:'step',text:'2'},{key:'marks',text:'0|2|4|6|8|10'},{key:'hidden',text:'4'}],['4'],'medium',9),
    A(126,2,'puzzle','Ghép',[{key:'slot_1',text:'Số lớn nhất 0-9'},{key:'token_9',text:'9'},{key:'token_10',text:'10'}],{slot_1:'token_9'},'medium',10),
    A(126,3,'fill_blank','Số lớn nhất có 1 chữ số là [b1]',[{key:'b1',text:''}],{b1:'9'},'hard',1),
    A(126,3,'fill_blank','[b1] > 6 và [b1] < 8, [b1] = ?',[{key:'b1',text:''}],{b1:'7'},'hard',2),
    A(126,3,'puzzle','Điền dấu',[{key:'slot_1',text:'9 _ 10'},{key:'slot_2',text:'5 _ 5'},{key:'token_lt',text:'<'},{key:'token_eq',text:'='}],{slot_1:'token_lt',slot_2:'token_eq'},'hard',3),
    A(126,3,'puzzle','Ghép',[{key:'slot_1',text:'Số liền sau 9'},{key:'slot_2',text:'Số liền trước 6'},{key:'token_10',text:'10'},{key:'token_5',text:'5'}],{slot_1:'token_10',slot_2:'token_5'},'hard',4),
    A(126,3,'game','Ghép',[{key:'c1',text:'3<5',pair:'dung'},{key:'c2',text:'7>4',pair:'dung'},{key:'c3',text:'6=6',pair:'dung'},{key:'c4',text:'2>8',pair:'sai'},{key:'c5',text:'9<3',pair:'sai'},{key:'c6',text:'5>7',pair:'sai'}],{},'hard',5),
    A(126,3,'sorting','Sắp xếp: 10,1,7,4,8',[{key:'1',text:'10'},{key:'2',text:'1'},{key:'3',text:'7'},{key:'4',text:'4'},{key:'5',text:'8'}],['2','4','3','5','1'],'hard',6),
    A(126,3,'matching','Nối',[{key:'A',text:'7+2'},{key:'B',text:'5+5'},{key:'C',text:'8-1'}],{A:'9',B:'10',C:'7'},'hard',7),
    A(126,3,'multiple_choice','Số nào nằm giữa 5 và 8?',[{key:'A',text:'4'},{key:'B',text:'6'},{key:'C',text:'7'},{key:'D',text:'9'}],['B','C'],'hard',8),
    A(126,3,'multiple_choice','Phép so sánh sai?',[{key:'A',text:'8>7'},{key:'B',text:'3<1'},{key:'C',text:'5>9'},{key:'D',text:'6<10'}],['B','C'],'hard',9),
    A(126,3,'drag_drop','Sắp xếp giảm dần: 3,8,5,10,7',[{key:'1',text:'3'},{key:'2',text:'8'},{key:'3',text:'5'},{key:'4',text:'10'},{key:'5',text:'7'}],['4','2','5','3','1'],'hard',10),
  ]),
  // ── 127: Mấy và mấy ──
  ...([
    A(127,1,'single_choice','3 và mấy bằng 5?',[{key:'A',text:'1'},{key:'B',text:'2'},{key:'C',text:'3'}],'B','easy',1),
    A(127,1,'single_choice','4 và 4 bằng?',[{key:'A',text:'7'},{key:'B',text:'8'},{key:'C',text:'9'}],'B','easy',2),
    A(127,1,'single_choice','2 và 6 bằng?',[{key:'A',text:'7'},{key:'B',text:'8'},{key:'C',text:'9'}],'B','easy',3),
    A(127,1,'true_false','5 = 2 + 3. Đúng hay sai?',null,true,'easy',4),
    A(127,1,'true_false','8 = 5 + 4. Đúng hay sai?',null,false,'easy',5),
    A(127,1,'fill_blank','7 = 3 + [b1]',[{key:'b1',text:''}],{b1:'4'},'easy',6),
    A(127,1,'fill_blank','[b1] + 5 = 9',[{key:'b1',text:''}],{b1:'4'},'easy',7),
    A(127,1,'counting','Đếm: 🍊🍊🍊🍊🍊🍊🍊',[{key:'d1',text:'🍊'},{key:'d2',text:'🍊'},{key:'d3',text:'🍊'},{key:'d4',text:'🍊'},{key:'d5',text:'🍊'},{key:'d6',text:'🍊'},{key:'d7',text:'🍊'}],'7','easy',8),
    A(127,1,'sorting','Sắp xếp tổng tăng dần: 2+3, 1+1, 4+4',[{key:'1',text:'2+3'},{key:'2',text:'1+1'},{key:'3',text:'4+4'}],['2','1','3'],'easy',9),
    A(127,1,'cross_out','Gạch bỏ phép tách sai của 6',[{key:'A',text:'4+2'},{key:'B',text:'3+4'},{key:'C',text:'1+5'},{key:'D',text:'2+5'}],['B','D'],'easy',10),
    A(127,2,'single_choice','10 = 6 + ?',[{key:'A',text:'3'},{key:'B',text:'4'},{key:'C',text:'5'}],'B','medium',1),
    A(127,2,'single_choice','8 = ? + 5',[{key:'A',text:'2'},{key:'B',text:'3'},{key:'C',text:'4'}],'B','medium',2),
    A(127,2,'multiple_choice','Cách nào tách số 7?',[{key:'A',text:'3+4'},{key:'B',text:'2+5'},{key:'C',text:'4+4'},{key:'D',text:'6+1'}],['A','B','D'],'medium',3),
    A(127,2,'multiple_choice','Cách nào tách số 9?',[{key:'A',text:'5+4'},{key:'B',text:'6+3'},{key:'C',text:'5+5'},{key:'D',text:'7+2'}],['A','B','D'],'medium',4),
    A(127,2,'matching','Nối phần tách',[{key:'A',text:'8'},{key:'B',text:'6'},{key:'C',text:'10'}],{A:'5+3',B:'2+4',C:'4+6'},'medium',5),
    A(127,2,'matching','Nối',[{key:'A',text:'4+?=7'},{key:'B',text:'?+2=8'},{key:'C',text:'5+?=9'}],{A:'3',B:'6',C:'4'},'medium',6),
    A(127,2,'drag_drop','Sắp xếp các cách tách 10',[{key:'1',text:'1+9'},{key:'2',text:'5+5'},{key:'3',text:'3+7'}],['1','3','2'],'medium',7),
    A(127,2,'table_fill','Điền bảng tách số',[{key:'headers',text:'Số|Phần 1|Phần 2'},{key:'r1',text:'9|4|_r1c1'},{key:'r2',text:'8|_r2c1|3'}],{r1c1:'5',r2c1:'5'},'medium',8),
    A(127,2,'number_line','Điền số thiếu',[{key:'min',text:'0'},{key:'max',text:'10'},{key:'step',text:'1'},{key:'marks',text:'0|1|2|3|4|5|6|7|8|9|10'},{key:'hidden',text:'5'}],['5'],'medium',9),
    A(127,2,'puzzle','Ghép',[{key:'slot_1',text:'? + 3 = 8'},{key:'token_5',text:'5'},{key:'token_4',text:'4'}],{slot_1:'token_5'},'medium',10),
    A(127,3,'fill_blank','10 = [b1] + 6',[{key:'b1',text:''}],{b1:'4'},'hard',1),
    A(127,3,'fill_blank','[b1] + [b1] = 8 (hai số bằng nhau)',[{key:'b1',text:''}],{b1:'4'},'hard',2),
    A(127,3,'puzzle','Ghép',[{key:'slot_1',text:'? + 4 = 9'},{key:'slot_2',text:'6 + ? = 10'},{key:'token_5',text:'5'},{key:'token_4',text:'4'}],{slot_1:'token_5',slot_2:'token_4'},'hard',3),
    A(127,3,'puzzle','Ghép',[{key:'slot_1',text:'10 = 7 + ?'},{key:'slot_2',text:'10 = ? + 6'},{key:'token_3',text:'3'},{key:'token_4',text:'4'}],{slot_1:'token_3',slot_2:'token_4'},'hard',4),
    A(127,3,'game','Ghép cặp tổng = 10',[{key:'c1',text:'4',pair:'bon_sau'},{key:'c2',text:'6',pair:'bon_sau'},{key:'c3',text:'3',pair:'ba_bay'},{key:'c4',text:'7',pair:'ba_bay'},{key:'c5',text:'2',pair:'hai_tam'},{key:'c6',text:'8',pair:'hai_tam'}],{},'hard',5),
    A(127,3,'sorting','Sắp xếp tổng: 6+1, 3+3, 5+4, 2+2',[{key:'1',text:'6+1'},{key:'2',text:'3+3'},{key:'3',text:'5+4'},{key:'4',text:'2+2'}],['4','2','1','3'],'hard',6),
    A(127,3,'matching','Nối',[{key:'A',text:'9 = ? + 5'},{key:'B',text:'9 = 6 + ?'},{key:'C',text:'9 = ? + 2'}],{A:'4',B:'3',C:'7'},'hard',7),
    A(127,3,'multiple_choice','Phép tách nào của 8 là đúng?',[{key:'A',text:'3+5'},{key:'B',text:'4+4'},{key:'C',text:'6+3'},{key:'D',text:'2+6'}],['A','B','D'],'hard',8),
    A(127,3,'multiple_choice','Cặp số nào có tổng = 9?',[{key:'A',text:'4+5'},{key:'B',text:'3+6'},{key:'C',text:'5+5'},{key:'D',text:'7+2'}],['A','B','D'],'hard',9),
    A(127,3,'drag_drop','Sắp xếp cặp tổng: 1+9, 4+6, 2+8, 5+5',[{key:'1',text:'1+9'},{key:'2',text:'4+6'},{key:'3',text:'2+8'},{key:'4',text:'5+5'}],['1','3','2','4'],'hard',10),
  ]),
  // ── 128: Luyện tập chung ──
  ...([
    A(128,1,'single_choice','5 + 3 = ?',[{key:'A',text:'7'},{key:'B',text:'8'},{key:'C',text:'9'}],'B','easy',1),
    A(128,1,'single_choice','9 - 4 = ?',[{key:'A',text:'4'},{key:'B',text:'5'},{key:'C',text:'6'}],'B','easy',2),
    A(128,1,'single_choice','Số lớn nhất trong 0,3,7,5 là?',[{key:'A',text:'5'},{key:'B',text:'7'},{key:'C',text:'3'}],'B','easy',3),
    A(128,1,'true_false','4 + 4 = 8. Đúng hay sai?',null,true,'easy',4),
    A(128,1,'true_false','6 > 8. Đúng hay sai?',null,false,'easy',5),
    A(128,1,'fill_blank','[b1] + 3 = 8',[{key:'b1',text:''}],{b1:'5'},'easy',6),
    A(128,1,'fill_blank','10 - [b1] = 6',[{key:'b1',text:''}],{b1:'4'},'easy',7),
    A(128,1,'counting','Đếm: 🐸🐸🐸🐸🐸🐸🐸🐸🐸',[{key:'d1',text:'🐸'},{key:'d2',text:'🐸'},{key:'d3',text:'🐸'},{key:'d4',text:'🐸'},{key:'d5',text:'🐸'},{key:'d6',text:'🐸'},{key:'d7',text:'🐸'},{key:'d8',text:'🐸'},{key:'d9',text:'🐸'}],'9','easy',8),
    A(128,1,'sorting','Sắp xếp: 5,2,8,1,6',[{key:'1',text:'5'},{key:'2',text:'2'},{key:'3',text:'8'},{key:'4',text:'1'},{key:'5',text:'6'}],['4','2','1','5','3'],'easy',9),
    A(128,1,'cross_out','Gạch số sai',[{key:'A',text:'2+3=5'},{key:'B',text:'4+3=8'},{key:'C',text:'6+2=8'},{key:'D',text:'5+4=8'}],['B','D'],'easy',10),
    A(128,2,'single_choice','7 + 3 = ?',[{key:'A',text:'9'},{key:'B',text:'10'},{key:'C',text:'11'}],'B','medium',1),
    A(128,2,'single_choice','10 - 7 = ?',[{key:'A',text:'2'},{key:'B',text:'3'},{key:'C',text:'4'}],'B','medium',2),
    A(128,2,'multiple_choice','Phép tính nào có kết quả là 7?',[{key:'A',text:'3+4'},{key:'B',text:'5+2'},{key:'C',text:'6+2'},{key:'D',text:'9-2'}],['A','B','D'],'medium',3),
    A(128,2,'multiple_choice','Số nào lớn hơn 5 và nhỏ hơn 9?',[{key:'A',text:'4'},{key:'B',text:'6'},{key:'C',text:'7'},{key:'D',text:'10'}],['B','C'],'medium',4),
    A(128,2,'matching','Nối',[{key:'A',text:'3+5'},{key:'B',text:'10-1'},{key:'C',text:'4+6'}],{A:'8',B:'9',C:'10'},'medium',5),
    A(128,2,'matching','Nối',[{key:'A',text:'Số liền sau 7'},{key:'B',text:'Số liền trước 5'},{key:'C',text:'8 = 4 + ?'}],{A:'8',B:'4',C:'4'},'medium',6),
    A(128,2,'drag_drop','Sắp xếp: 10,3,7,5,8',[{key:'1',text:'10'},{key:'2',text:'3'},{key:'3',text:'7'},{key:'4',text:'5'},{key:'5',text:'8'}],['2','4','3','5','1'],'medium',7),
    A(128,2,'table_fill','Điền bảng',[{key:'headers',text:'Phép tính|Kết quả'},{key:'r1',text:'4+5|_r1c1'},{key:'r2',text:'10-3|_r2c1'}],{r1c1:'9',r2c1:'7'},'medium',8),
    A(128,2,'number_line','Điền số thiếu',[{key:'min',text:'0'},{key:'max',text:'10'},{key:'step',text:'1'},{key:'marks',text:'0|2|4|6|8|10'},{key:'hidden',text:'8'}],['8'],'medium',9),
    A(128,2,'puzzle','Ghép',[{key:'slot_1',text:'? + 4 = 10'},{key:'token_6',text:'6'},{key:'token_5',text:'5'}],{slot_1:'token_6'},'medium',10),
    A(128,3,'fill_blank','[b1] - 4 = 5',[{key:'b1',text:''}],{b1:'9'},'hard',1),
    A(128,3,'fill_blank','8 = [b1] + 3',[{key:'b1',text:''}],{b1:'5'},'hard',2),
    A(128,3,'puzzle','Ghép',[{key:'slot_1',text:'8 = ? + 5'},{key:'slot_2',text:'? - 3 = 7'},{key:'token_3',text:'3'},{key:'token_10',text:'10'}],{slot_1:'token_3',slot_2:'token_10'},'hard',3),
    A(128,3,'puzzle','Ghép',[{key:'slot_1',text:'6 + ? = 10'},{key:'slot_2',text:'? - 5 = 4'},{key:'token_4',text:'4'},{key:'token_9',text:'9'}],{slot_1:'token_4',slot_2:'token_9'},'hard',4),
    A(128,3,'game','Ghép cặp',[{key:'c1',text:'2+5',pair:'bay'},{key:'c2',text:'9-2',pair:'bay'},{key:'c3',text:'3+5',pair:'tam'},{key:'c4',text:'10-2',pair:'tam'},{key:'c5',text:'4+5',pair:'chin'},{key:'c6',text:'10-1',pair:'chin'}],{},'hard',5),
    A(128,3,'sorting','Sắp xếp: 3+4, 1+8, 2+5, 5+5',[{key:'1',text:'3+4'},{key:'2',text:'1+8'},{key:'3',text:'2+5'},{key:'4',text:'5+5'}],['1','3','2','4'],'hard',6),
    A(128,3,'matching','Nối',[{key:'A',text:'4+?=9'},{key:'B',text:'?+3=10'},{key:'C',text:'8-?=3'}],{A:'5',B:'7',C:'5'},'hard',7),
    A(128,3,'multiple_choice','Phép tính nào đúng?',[{key:'A',text:'5+5=10'},{key:'B',text:'8-3=4'},{key:'C',text:'7+2=9'},{key:'D',text:'6+4=9'}],['A','C'],'hard',8),
    A(128,3,'multiple_choice','Tổng nào = 9?',[{key:'A',text:'4+5'},{key:'B',text:'3+6'},{key:'C',text:'2+8'},{key:'D',text:'7+2'}],['A','B','D'],'hard',9),
    A(128,3,'drag_drop','Sắp xếp tăng dần kết quả',[{key:'1',text:'3+3'},{key:'2',text:'2+4'},{key:'3',text:'5+5'},{key:'4',text:'4+3'}],['2','1','4','3'],'hard',10),
  ]),
  // ── 129: Hình học 2D ──
  ...([
    A(129,1,'single_choice','Hình nào có 3 cạnh?',[{key:'A',text:'Hình vuông'},{key:'B',text:'Hình tam giác'},{key:'C',text:'Hình tròn'}],'B','easy',1),
    A(129,1,'single_choice','Hình nào không có góc?',[{key:'A',text:'Hình tròn'},{key:'B',text:'Hình vuông'},{key:'C',text:'Hình chữ nhật'}],'A','easy',2),
    A(129,1,'single_choice','Hình vuông có mấy cạnh?',[{key:'A',text:'3'},{key:'B',text:'4'},{key:'C',text:'5'}],'B','easy',3),
    A(129,1,'true_false','Hình chữ nhật có 4 cạnh. Đúng hay sai?',null,true,'easy',4),
    A(129,1,'true_false','Hình tam giác có 4 góc. Đúng hay sai?',null,false,'easy',5),
    A(129,1,'fill_blank','Hình tròn có [b1] góc',[{key:'b1',text:''}],{b1:'0'},'easy',6),
    A(129,1,'fill_blank','Hình vuông có [b1] cạnh bằng nhau',[{key:'b1',text:''}],{b1:'4'},'easy',7),
    A(129,1,'counting','Đếm số hình tam giác: △△△△△',[{key:'d1',text:'△'},{key:'d2',text:'△'},{key:'d3',text:'△'},{key:'d4',text:'△'},{key:'d5',text:'△'}],'5','easy',8),
    A(129,1,'sorting','Sắp xếp theo số cạnh tăng dần',[{key:'1',text:'Hình tròn'},{key:'2',text:'Tam giác'},{key:'3',text:'Chữ nhật'}],['1','2','3'],'easy',9),
    A(129,1,'cross_out','Gạch bỏ hình không phải hình phẳng',[{key:'A',text:'Hình vuông'},{key:'B',text:'Khối hộp'},{key:'C',text:'Hình tròn'},{key:'D',text:'Khối cầu'}],['B','D'],'easy',10),
    A(129,2,'single_choice','Hình nào có tất cả cạnh bằng nhau?',[{key:'A',text:'Hình chữ nhật'},{key:'B',text:'Hình vuông'},{key:'C',text:'Hình tam giác'}],'B','medium',1),
    A(129,2,'single_choice','Vật nào có hình tròn?',[{key:'A',text:'Quyển sách'},{key:'B',text:'Đồng xu'},{key:'C',text:'Hộp bút'}],'B','medium',2),
    A(129,2,'multiple_choice','Hình nào có 4 cạnh?',[{key:'A',text:'Hình vuông'},{key:'B',text:'Hình tròn'},{key:'C',text:'Hình chữ nhật'},{key:'D',text:'Tam giác'}],['A','C'],'medium',3),
    A(129,2,'multiple_choice','Hình nào có góc?',[{key:'A',text:'Hình tròn'},{key:'B',text:'Hình vuông'},{key:'C',text:'Tam giác'},{key:'D',text:'Hình chữ nhật'}],['B','C','D'],'medium',4),
    A(129,2,'matching','Nối hình với số cạnh',[{key:'A',text:'Hình tròn'},{key:'B',text:'Tam giác'},{key:'C',text:'Hình vuông'}],{A:'0',B:'3',C:'4'},'medium',5),
    A(129,2,'matching','Nối vật với hình',[{key:'A',text:'Bánh xe'},{key:'B',text:'Viên gạch'},{key:'C',text:'Biển báo tam giác'}],{A:'Hình tròn',B:'Hình chữ nhật',C:'Tam giác'},'medium',6),
    A(129,2,'drag_drop','Sắp xếp hình theo số góc tăng dần',[{key:'1',text:'Hình vuông'},{key:'2',text:'Hình tròn'},{key:'3',text:'Tam giác'}],['2','3','1'],'medium',7),
    A(129,2,'table_fill','Điền bảng',[{key:'headers',text:'Hình|Số cạnh|Số góc'},{key:'r1',text:'Tam giác|_r1c1|_r1c2'},{key:'r2',text:'Hình vuông|_r2c1|_r2c2'}],{r1c1:'3',r1c2:'3',r2c1:'4',r2c2:'4'},'medium',8),
    A(129,2,'number_line','Đếm số hình vuông (0-5)',[{key:'min',text:'0'},{key:'max',text:'5'},{key:'step',text:'1'},{key:'marks',text:'0|1|2|3|4|5'},{key:'hidden',text:'3'}],['3'],'medium',9),
    A(129,2,'puzzle','Ghép hình với đặc điểm',[{key:'slot_1',text:'Có 3 cạnh, 3 góc'},{key:'token_tg',text:'Tam giác'},{key:'token_ht',text:'Hình tròn'}],{slot_1:'token_tg'},'medium',10),
    A(129,3,'fill_blank','Hình chữ nhật có [b1] cạnh dài và [b1] cạnh ngắn',[{key:'b1',text:''}],{b1:'2'},'hard',1),
    A(129,3,'fill_blank','Tổng số cạnh của 2 tam giác là [b1]',[{key:'b1',text:''}],{b1:'6'},'hard',2),
    A(129,3,'puzzle','Ghép',[{key:'slot_1',text:'Có 4 cạnh bằng nhau'},{key:'slot_2',text:'Không có góc'},{key:'token_hv',text:'Hình vuông'},{key:'token_ht',text:'Hình tròn'}],{slot_1:'token_hv',slot_2:'token_ht'},'hard',3),
    A(129,3,'puzzle','Ghép',[{key:'slot_1',text:'3 cạnh'},{key:'slot_2',text:'4 cạnh, 2 cạnh dài bằng nhau'},{key:'token_tg',text:'Tam giác'},{key:'token_hcn',text:'Hình chữ nhật'}],{slot_1:'token_tg',slot_2:'token_hcn'},'hard',4),
    A(129,3,'game','Ghép hình với đặc điểm',[{key:'c1',text:'Hình tròn',pair:'khong_canh'},{key:'c2',text:'0 cạnh',pair:'khong_canh'},{key:'c3',text:'Tam giác',pair:'ba_canh'},{key:'c4',text:'3 cạnh',pair:'ba_canh'},{key:'c5',text:'Hình vuông',pair:'bon_canh'},{key:'c6',text:'4 cạnh bằng nhau',pair:'bon_canh'}],{},'hard',5),
    A(129,3,'sorting','Sắp xếp theo số cạnh tăng dần',[{key:'1',text:'Hình vuông'},{key:'2',text:'Hình tròn'},{key:'3',text:'Tam giác'},{key:'4',text:'Hình chữ nhật'}],['2','3','1','4'],'hard',6),
    A(129,3,'matching','Nối',[{key:'A',text:'Hình có 0 góc'},{key:'B',text:'Hình có 3 góc'},{key:'C',text:'Hình có 4 góc bằng nhau'}],{A:'Hình tròn',B:'Tam giác',C:'Hình vuông'},'hard',7),
    A(129,3,'multiple_choice','Điểm giống nhau của hình vuông và chữ nhật?',[{key:'A',text:'4 cạnh bằng nhau'},{key:'B',text:'4 cạnh'},{key:'C',text:'4 góc'},{key:'D',text:'Không có đường cong'}],['B','C','D'],'hard',8),
    A(129,3,'multiple_choice','Hình nào KHÔNG có trong bộ hình phẳng lớp 1?',[{key:'A',text:'Hình thoi'},{key:'B',text:'Hình tròn'},{key:'C',text:'Ngũ giác'},{key:'D',text:'Hình vuông'}],['A','C'],'hard',9),
    A(129,3,'drag_drop','Sắp xếp: Tròn, Tam giác, Vuông, Chữ nhật theo số cạnh',[{key:'1',text:'Hình tròn'},{key:'2',text:'Tam giác'},{key:'3',text:'Hình vuông'},{key:'4',text:'Hình chữ nhật'}],['1','2','3','4'],'hard',10),
  ]),
  // ── 130: Thực hành lắp ghép, xếp hình ──
  ...([
    A(130,1,'single_choice','Ghép 2 tam giác bằng nhau thành hình gì?',[{key:'A',text:'Hình tròn'},{key:'B',text:'Hình chữ nhật'},{key:'C',text:'Hình vuông'}],'B','easy',1),
    A(130,1,'single_choice','Xếp 4 hình vuông nhỏ thành hình gì lớn?',[{key:'A',text:'Hình tròn'},{key:'B',text:'Tam giác'},{key:'C',text:'Hình vuông lớn'}],'C','easy',2),
    A(130,1,'single_choice','Cần mấy tam giác để ghép 1 hình chữ nhật?',[{key:'A',text:'1'},{key:'B',text:'2'},{key:'C',text:'3'}],'B','easy',3),
    A(130,1,'true_false','Có thể ghép 2 tam giác thành 1 hình vuông. Đúng hay sai?',null,true,'easy',4),
    A(130,1,'true_false','Hình tròn có thể ghép từ các mảnh thẳng. Đúng hay sai?',null,false,'easy',5),
    A(130,1,'fill_blank','Cần [b1] hình vuông nhỏ để ghép thành 1 hình chữ nhật 1×2',[{key:'b1',text:''}],{b1:'2'},'easy',6),
    A(130,1,'fill_blank','Một hình tam giác có [b1] cạnh',[{key:'b1',text:''}],{b1:'3'},'easy',7),
    A(130,1,'counting','Đếm số tam giác trong hình: △△△△',[{key:'d1',text:'△'},{key:'d2',text:'△'},{key:'d3',text:'△'},{key:'d4',text:'△'}],'4','easy',8),
    A(130,1,'sorting','Sắp xếp số mảnh từ ít đến nhiều',[{key:'1',text:'3 mảnh'},{key:'2',text:'1 mảnh'},{key:'3',text:'5 mảnh'},{key:'4',text:'2 mảnh'}],['2','4','1','3'],'easy',9),
    A(130,1,'cross_out','Gạch bỏ hình KHÔNG thể ghép từ tam giác',[{key:'A',text:'Hình chữ nhật'},{key:'B',text:'Hình tròn'},{key:'C',text:'Hình vuông'},{key:'D',text:'Hình oval'}],['B','D'],'easy',10),
    A(130,2,'single_choice','Ghép 4 tam giác nhỏ bằng nhau thành hình gì?',[{key:'A',text:'Hình tròn'},{key:'B',text:'Tam giác lớn'},{key:'C',text:'Hình vuông'}],'B','medium',1),
    A(130,2,'single_choice','Xếp gạch hình vuông thành hàng 3×2, cần mấy gạch?',[{key:'A',text:'5'},{key:'B',text:'6'},{key:'C',text:'7'}],'B','medium',2),
    A(130,2,'multiple_choice','Hình nào có thể ghép từ 2 hình vuông bằng nhau?',[{key:'A',text:'Hình chữ nhật'},{key:'B',text:'Hình tròn'},{key:'C',text:'Hình lớn hơn'},{key:'D',text:'Hình vuông lớn hơn'}],['A'],'medium',3),
    A(130,2,'multiple_choice','Để xếp hình chữ nhật 2×3, cần?',[{key:'A',text:'4 ô vuông'},{key:'B',text:'5 ô vuông'},{key:'C',text:'6 ô vuông'},{key:'D',text:'3 ô vuông'}],['C'],'medium',4),
    A(130,2,'matching','Nối hình ghép với kết quả',[{key:'A',text:'2 tam giác bằng nhau'},{key:'B',text:'2 hình vuông bằng nhau'},{key:'C',text:'4 ô vuông'}],{A:'Hình chữ nhật',B:'Hình chữ nhật',C:'Hình chữ nhật 2×2'},'medium',5),
    A(130,2,'matching','Nối',[{key:'A',text:'3 cạnh'},{key:'B',text:'4 cạnh bằng nhau'},{key:'C',text:'4 cạnh, 2 đôi bằng nhau'}],{A:'Tam giác',B:'Hình vuông',C:'Hình chữ nhật'},'medium',6),
    A(130,2,'drag_drop','Sắp xếp bước xếp hình',[{key:'1',text:'Chọn mảnh'},{key:'2',text:'Đặt mảnh đầu tiên'},{key:'3',text:'Ghép mảnh tiếp theo'},{key:'4',text:'Kiểm tra hình hoàn chỉnh'}],['1','2','3','4'],'medium',7),
    A(130,2,'table_fill','Điền bảng',[{key:'headers',text:'Số hình nhỏ|Hình tạo thành'},{key:'r1',text:'2|_r1c1'},{key:'r2',text:'4|_r2c1'}],{r1c1:'Hình chữ nhật',r2c1:'Hình vuông lớn'},'medium',8),
    A(130,2,'number_line','Số ô vuông trong hàng 1×N',[{key:'min',text:'1'},{key:'max',text:'6'},{key:'step',text:'1'},{key:'marks',text:'1|2|3|4|5|6'},{key:'hidden',text:'4'}],['4'],'medium',9),
    A(130,2,'puzzle','Ghép',[{key:'slot_1',text:'2 tam giác = 1 ?'},{key:'token_hcn',text:'Hình chữ nhật'},{key:'token_ht',text:'Hình tròn'}],{slot_1:'token_hcn'},'medium',10),
    A(130,3,'fill_blank','Hàng 2×4 ô vuông có tổng [b1] ô',[{key:'b1',text:''}],{b1:'8'},'hard',1),
    A(130,3,'fill_blank','Cần [b1] tam giác nhỏ để ghép 1 tam giác lớn (4 tam giác = 1)',[{key:'b1',text:''}],{b1:'4'},'hard',2),
    A(130,3,'puzzle','Ghép',[{key:'slot_1',text:'2×3 ô vuông = ? ô'},{key:'token_6',text:'6'},{key:'token_5',text:'5'}],{slot_1:'token_6'},'hard',3),
    A(130,3,'puzzle','Ghép',[{key:'slot_1',text:'Chia hình chữ nhật = 2 phần bằng nhau → mỗi phần là?'},{key:'token_hv',text:'Hình vuông'},{key:'token_tg',text:'Tam giác'}],{slot_1:'token_hv'},'hard',4),
    A(130,3,'game','Ghép hình',[{key:'c1',text:'2 tam giác',pair:'hinh_cn'},{key:'c2',text:'Hình chữ nhật nhỏ',pair:'hinh_cn'},{key:'c3',text:'4 ô vuông',pair:'hinh_2x2'},{key:'c4',text:'Hình vuông 2×2',pair:'hinh_2x2'},{key:'c5',text:'3 hình vuông',pair:'hinh_1x3'},{key:'c6',text:'Hình chữ nhật 1×3',pair:'hinh_1x3'}],{},'hard',5),
    A(130,3,'sorting','Sắp xếp theo diện tích tăng dần',[{key:'1',text:'2×2'},{key:'2',text:'1×2'},{key:'3',text:'3×3'},{key:'4',text:'1×3'}],['2','4','1','3'],'hard',6),
    A(130,3,'matching','Nối',[{key:'A',text:'2 ô×2 ô'},{key:'B',text:'3 ô×2 ô'},{key:'C',text:'4 ô×1 ô'}],{A:'4 ô',B:'6 ô',C:'4 ô'},'hard',7),
    A(130,3,'multiple_choice','Ghép 2 hình vuông cùng kích thước tạo ra?',[{key:'A',text:'Hình chữ nhật'},{key:'B',text:'Hình tròn'},{key:'C',text:'Tam giác lớn'},{key:'D',text:'Hình vuông nhỏ hơn'}],['A'],'hard',8),
    A(130,3,'multiple_choice','Hàng 1×5 và 1×3 có tổng bao nhiêu ô?',[{key:'A',text:'7'},{key:'B',text:'8'},{key:'C',text:'9'},{key:'D',text:'10'}],['B'],'hard',9),
    A(130,3,'drag_drop','Sắp xếp số ô: 2×3, 1×4, 3×3, 2×2',[{key:'1',text:'2×3=6'},{key:'2',text:'1×4=4'},{key:'3',text:'3×3=9'},{key:'4',text:'2×2=4'}],['2','4','1','3'],'hard',10),
  ]),
  // ── 131: Luyện tập chung hình học ──
  ...([
    A(131,1,'single_choice','Hình tròn có mấy cạnh?',[{key:'A',text:'0'},{key:'B',text:'1'},{key:'C',text:'2'}],'A','easy',1),
    A(131,1,'single_choice','Có mấy loại hình phẳng đã học?',[{key:'A',text:'3'},{key:'B',text:'4'},{key:'C',text:'5'}],'B','easy',2),
    A(131,1,'single_choice','Hình nào sau đây là hình phẳng?',[{key:'A',text:'Khối cầu'},{key:'B',text:'Hình tròn'},{key:'C',text:'Khối hộp'}],'B','easy',3),
    A(131,1,'true_false','Hình vuông và hình chữ nhật đều có 4 cạnh. Đúng hay sai?',null,true,'easy',4),
    A(131,1,'true_false','Tam giác có 4 góc. Đúng hay sai?',null,false,'easy',5),
    A(131,1,'fill_blank','Tổng số cạnh của 1 tam giác và 1 hình vuông là [b1]',[{key:'b1',text:''}],{b1:'7'},'easy',6),
    A(131,1,'fill_blank','Hình chữ nhật có [b1] cặp cạnh song song',[{key:'b1',text:''}],{b1:'2'},'easy',7),
    A(131,1,'counting','Đếm số hình vuông: □□□',[{key:'d1',text:'□'},{key:'d2',text:'□'},{key:'d3',text:'□'}],'3','easy',8),
    A(131,1,'sorting','Sắp xếp theo số cạnh: Tam giác, Hình tròn, Hình vuông, Chữ nhật',[{key:'1',text:'Tam giác'},{key:'2',text:'Hình tròn'},{key:'3',text:'Hình vuông'},{key:'4',text:'Hình chữ nhật'}],['2','1','3','4'],'easy',9),
    A(131,1,'cross_out','Gạch bỏ hình không phải hình phẳng',[{key:'A',text:'Hình vuông'},{key:'B',text:'Khối lập phương'},{key:'C',text:'Hình tròn'},{key:'D',text:'Khối trụ'}],['B','D'],'easy',10),
    A(131,2,'single_choice','Ghép 2 hình vuông = ?',[{key:'A',text:'Hình tròn'},{key:'B',text:'Hình chữ nhật'},{key:'C',text:'Tam giác'}],'B','medium',1),
    A(131,2,'single_choice','Xếp 3×2 ô vuông cần mấy ô?',[{key:'A',text:'5'},{key:'B',text:'6'},{key:'C',text:'7'}],'B','medium',2),
    A(131,2,'multiple_choice','Hình nào có số cạnh nhiều hơn tam giác?',[{key:'A',text:'Hình tròn'},{key:'B',text:'Hình vuông'},{key:'C',text:'Hình chữ nhật'},{key:'D',text:'Tam giác'}],['B','C'],'medium',3),
    A(131,2,'multiple_choice','Hình nào giống hình vuông về số cạnh?',[{key:'A',text:'Tam giác'},{key:'B',text:'Hình chữ nhật'},{key:'C',text:'Tứ giác'},{key:'D',text:'Hình tròn'}],['B','C'],'medium',4),
    A(131,2,'matching','Nối hình với đặc điểm',[{key:'A',text:'Hình tròn'},{key:'B',text:'Tam giác'},{key:'C',text:'Hình chữ nhật'}],{A:'Không có góc',B:'3 cạnh',C:'4 cạnh 2 đôi'},'medium',5),
    A(131,2,'matching','Nối',[{key:'A',text:'Bánh xe'},{key:'B',text:'Gạch'},{key:'C',text:'Biển báo 3 góc'}],{A:'Tròn',B:'Chữ nhật',C:'Tam giác'},'medium',6),
    A(131,2,'drag_drop','Sắp xếp theo số góc tăng dần',[{key:'1',text:'Hình vuông'},{key:'2',text:'Hình tròn'},{key:'3',text:'Tam giác'},{key:'4',text:'Hình chữ nhật'}],['2','3','1','4'],'medium',7),
    A(131,2,'table_fill','Điền bảng',[{key:'headers',text:'Hình|Cạnh|Góc'},{key:'r1',text:'Tam giác|_r1c1|_r1c2'},{key:'r2',text:'Hình chữ nhật|_r2c1|_r2c2'}],{r1c1:'3',r1c2:'3',r2c1:'4',r2c2:'4'},'medium',8),
    A(131,2,'number_line','Đếm tổng cạnh',[{key:'min',text:'0'},{key:'max',text:'10'},{key:'step',text:'1'},{key:'marks',text:'0|1|2|3|4|5|6|7|8|9|10'},{key:'hidden',text:'7'}],['7'],'medium',9),
    A(131,2,'puzzle','Ghép',[{key:'slot_1',text:'3 cạnh + 3 góc'},{key:'token_tg',text:'Tam giác'},{key:'token_hv',text:'Hình vuông'}],{slot_1:'token_tg'},'medium',10),
    A(131,3,'fill_blank','Tổng cạnh của 2 hình vuông là [b1]',[{key:'b1',text:''}],{b1:'8'},'hard',1),
    A(131,3,'fill_blank','Tổng góc của 1 tam giác + 1 hình chữ nhật là [b1]',[{key:'b1',text:''}],{b1:'7'},'hard',2),
    A(131,3,'puzzle','Ghép',[{key:'slot_1',text:'4 cạnh + 4 góc bằng nhau'},{key:'slot_2',text:'0 cạnh'},{key:'token_hv',text:'Hình vuông'},{key:'token_ht',text:'Hình tròn'}],{slot_1:'token_hv',slot_2:'token_ht'},'hard',3),
    A(131,3,'puzzle','Ghép',[{key:'slot_1',text:'2 tam giác → ?'},{key:'slot_2',text:'2 hình vuông → ?'},{key:'token_hcn',text:'Hình chữ nhật'},{key:'token_hcnl',text:'Hình chữ nhật lớn'}],{slot_1:'token_hcn',slot_2:'token_hcnl'},'hard',4),
    A(131,3,'game','Ghép',[{key:'c1',text:'Hình tròn',pair:'khong_goc'},{key:'c2',text:'0 góc',pair:'khong_goc'},{key:'c3',text:'Tam giác',pair:'ba_goc'},{key:'c4',text:'3 góc',pair:'ba_goc'},{key:'c5',text:'Hình vuông',pair:'bon_goc'},{key:'c6',text:'4 góc bằng nhau',pair:'bon_goc'}],{},'hard',5),
    A(131,3,'sorting','Sắp xếp theo số cạnh: Tròn, Tam giác, Vuông, Chữ nhật',[{key:'1',text:'Hình tròn'},{key:'2',text:'Tam giác'},{key:'3',text:'Hình vuông'},{key:'4',text:'Hình chữ nhật'}],['1','2','3','4'],'hard',6),
    A(131,3,'matching','Nối',[{key:'A',text:'Không có cạnh thẳng'},{key:'B',text:'3 cạnh bằng nhau'},{key:'C',text:'4 cạnh bằng nhau'}],{A:'Hình tròn',B:'Tam giác đều',C:'Hình vuông'},'hard',7),
    A(131,3,'multiple_choice','Điểm chung của vuông và chữ nhật?',[{key:'A',text:'4 cạnh'},{key:'B',text:'4 góc'},{key:'C',text:'4 cạnh bằng nhau'},{key:'D',text:'Hình phẳng'}],['A','B','D'],'hard',8),
    A(131,3,'multiple_choice','Hình nào KHÔNG phải hình phẳng?',[{key:'A',text:'Khối cầu'},{key:'B',text:'Hình vuông'},{key:'C',text:'Khối hộp'},{key:'D',text:'Hình tròn'}],['A','C'],'hard',9),
    A(131,3,'drag_drop','Sắp xếp theo số cạnh tăng dần',[{key:'1',text:'Hình chữ nhật'},{key:'2',text:'Hình tròn'},{key:'3',text:'Tam giác'},{key:'4',text:'Hình vuông'}],['2','3','4','1'],'hard',10),
  ]),
  // ── 132: Phép cộng trong phạm vi 10 ──
  ...([
    A(132,1,'single_choice','3 + 4 = ?',[{key:'A',text:'6'},{key:'B',text:'7'},{key:'C',text:'8'}],'B','easy',1),
    A(132,1,'single_choice','5 + 2 = ?',[{key:'A',text:'6'},{key:'B',text:'7'},{key:'C',text:'8'}],'B','easy',2),
    A(132,1,'single_choice','0 + 6 = ?',[{key:'A',text:'5'},{key:'B',text:'6'},{key:'C',text:'7'}],'B','easy',3),
    A(132,1,'true_false','4 + 5 = 9. Đúng hay sai?',null,true,'easy',4),
    A(132,1,'true_false','3 + 3 = 7. Đúng hay sai?',null,false,'easy',5),
    A(132,1,'fill_blank','6 + [b1] = 10',[{key:'b1',text:''}],{b1:'4'},'easy',6),
    A(132,1,'fill_blank','[b1] + 3 = 8',[{key:'b1',text:''}],{b1:'5'},'easy',7),
    A(132,1,'counting','Đếm: 🍎🍎🍎 + 🍎🍎 = mấy? (5 quả)',[{key:'d1',text:'🍎'},{key:'d2',text:'🍎'},{key:'d3',text:'🍎'},{key:'d4',text:'🍎'},{key:'d5',text:'🍎'}],'5','easy',8),
    A(132,1,'sorting','Sắp xếp tổng tăng dần: 2+1, 4+3, 1+1',[{key:'1',text:'2+1'},{key:'2',text:'4+3'},{key:'3',text:'1+1'}],['3','1','2'],'easy',9),
    A(132,1,'cross_out','Gạch bỏ phép cộng có tổng > 10',[{key:'A',text:'5+6'},{key:'B',text:'4+3'},{key:'C',text:'7+4'},{key:'D',text:'3+6'}],['A','C'],'easy',10),
    A(132,2,'single_choice','7 + 3 = ?',[{key:'A',text:'9'},{key:'B',text:'10'},{key:'C',text:'11'}],'B','medium',1),
    A(132,2,'single_choice','Tổng của 4 và 5 là?',[{key:'A',text:'8'},{key:'B',text:'9'},{key:'C',text:'10'}],'B','medium',2),
    A(132,2,'multiple_choice','Phép tính nào có tổng = 8?',[{key:'A',text:'3+5'},{key:'B',text:'4+4'},{key:'C',text:'6+3'},{key:'D',text:'2+6'}],['A','B','D'],'medium',3),
    A(132,2,'multiple_choice','Tổng nào = 10?',[{key:'A',text:'5+5'},{key:'B',text:'4+6'},{key:'C',text:'7+3'},{key:'D',text:'4+5'}],['A','B','C'],'medium',4),
    A(132,2,'matching','Nối phép tính với tổng',[{key:'A',text:'3+4'},{key:'B',text:'5+5'},{key:'C',text:'6+3'}],{A:'7',B:'10',C:'9'},'medium',5),
    A(132,2,'matching','Nối',[{key:'A',text:'Tổng của 4 và 6'},{key:'B',text:'3 cộng với 7'},{key:'C',text:'5 + 4'}],{A:'10',B:'10',C:'9'},'medium',6),
    A(132,2,'drag_drop','Sắp xếp tổng tăng dần',[{key:'1',text:'3+5'},{key:'2',text:'2+3'},{key:'3',text:'4+6'},{key:'4',text:'3+4'}],['2','4','1','3'],'medium',7),
    A(132,2,'table_fill','Điền kết quả',[{key:'headers',text:'Phép cộng|Tổng'},{key:'r1',text:'6+3|_r1c1'},{key:'r2',text:'5+5|_r2c1'}],{r1c1:'9',r2c1:'10'},'medium',8),
    A(132,2,'number_line','Tổng 5+?=9',[{key:'min',text:'0'},{key:'max',text:'10'},{key:'step',text:'1'},{key:'marks',text:'0|2|4|6|8|10'},{key:'hidden',text:'4'}],['4'],'medium',9),
    A(132,2,'puzzle','Ghép',[{key:'slot_1',text:'? + 5 = 10'},{key:'token_5',text:'5'},{key:'token_4',text:'4'}],{slot_1:'token_5'},'medium',10),
    A(132,3,'fill_blank','[b1] + 7 = 10',[{key:'b1',text:''}],{b1:'3'},'hard',1),
    A(132,3,'fill_blank','5 + [b1] = 5 + 3 = [b1]',[{key:'b1',text:''}],{b1:'3'},'hard',2),
    A(132,3,'puzzle','Ghép',[{key:'slot_1',text:'? + 6 = 10'},{key:'slot_2',text:'4 + ? = 10'},{key:'token_4',text:'4'},{key:'token_6',text:'6'}],{slot_1:'token_4',slot_2:'token_6'},'hard',3),
    A(132,3,'puzzle','Ghép bảng cộng',[{key:'slot_1',text:'8 + ? = 10'},{key:'slot_2',text:'? + 9 = 10'},{key:'token_2',text:'2'},{key:'token_1',text:'1'}],{slot_1:'token_2',slot_2:'token_1'},'hard',4),
    A(132,3,'game','Ghép cặp tổng',[{key:'c1',text:'3+5',pair:'tam'},{key:'c2',text:'6+2',pair:'tam'},{key:'c3',text:'5+4',pair:'chin'},{key:'c4',text:'7+2',pair:'chin'},{key:'c5',text:'5+5',pair:'muoi'},{key:'c6',text:'4+6',pair:'muoi'}],{},'hard',5),
    A(132,3,'sorting','Sắp xếp tổng: 2+8, 1+6, 4+4, 3+5',[{key:'1',text:'2+8'},{key:'2',text:'1+6'},{key:'3',text:'4+4'},{key:'4',text:'3+5'}],['2','3','4','1'],'hard',6),
    A(132,3,'matching','Nối',[{key:'A',text:'5 + ? = 8'},{key:'B',text:'3 + ? = 10'},{key:'C',text:'6 + ? = 9'}],{A:'3',B:'7',C:'3'},'hard',7),
    A(132,3,'multiple_choice','Số hạng nào cộng với 6 bằng 10?',[{key:'A',text:'3'},{key:'B',text:'4'},{key:'C',text:'5'},{key:'D',text:'6'}],['B'],'hard',8),
    A(132,3,'multiple_choice','Phép cộng nào đúng?',[{key:'A',text:'7+4=10'},{key:'B',text:'5+4=9'},{key:'C',text:'6+4=10'},{key:'D',text:'3+7=9'}],['B','C'],'hard',9),
    A(132,3,'drag_drop','Sắp xếp tăng dần: 3+7, 4+3, 5+4, 2+5',[{key:'1',text:'3+7'},{key:'2',text:'4+3'},{key:'3',text:'5+4'},{key:'4',text:'2+5'}],['4','2','3','1'],'hard',10),
  ]),
];

async function main() {
  const conn = await mysql.createConnection(DB);
  const lessonIds = [123,124,125,126,127,128,129,130,131,132];
  for (const id of lessonIds) {
    await conn.query('DELETE FROM quizzes WHERE lessonId = ?', [id]);
  }
  console.log('Deleted existing quizzes for lessons 123-132');
  const byLesson = new Map<number, Q[]>();
  for (const q of QUIZZES) {
    if (!byLesson.has(q.lessonId)) byLesson.set(q.lessonId, []);
    byLesson.get(q.lessonId)!.push(q);
  }
  for (const [lessonId, qs] of byLesson) {
    for (const q of qs) {
      await conn.query(SQL, [
        lessonId, q.ex, q.type, q.text,
        q.opts ? JSON.stringify(q.opts) : null,
        JSON.stringify(q.ans),
        q.diff, (q as any).expl ?? null, 10, q.sort
      ]);
    }
    console.log(`✅ lessonId ${lessonId}: ${qs.length} questions`);
  }
  await conn.end();
  console.log('Done!');
}
main().catch(console.error);
