import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.join(__dirname, '../../.env') });

const ds = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [],
  synchronize: false,
});

type QuizType = 'single_choice' | 'true_false' | 'drag_drop' | 'matching';
type Difficulty = 'easy' | 'medium' | 'hard';

interface QuizSeed {
  questionText: string;
  questionType: QuizType;
  difficultyLevel: Difficulty;
  exerciseNumber: number;
  sortOrder: number;
  optionsJson?: { key: string; text: string }[];
  correctAnswerJson: unknown;
  explanation?: string;
}

// ─── Lesson data ─────────────────────────────────────────────────────────────

interface ChuCaiLesson {
  id: number;
  type: 'chu-cai';
  upper: string; lower: string;
  words: string[]; // 4 example words containing the letter
}
interface VanLesson {
  id: number;
  type: 'van';
  vanList: string[]; // e.g. ['an','ân','ăn']
  words: string[];   // example words with each rhyme
}
interface OnTapLesson {
  id: number;
  type: 'on-tap';
  topic: string;
}
interface DocHieuLesson {
  id: number;
  type: 'doc-hieu';
  story: string;   // story title
  topic: string;   // theme keyword
}

type LessonData = ChuCaiLesson | VanLesson | OnTapLesson | DocHieuLesson;

const LESSONS: LessonData[] = [
  // Bài 2-30: Chữ cái & chữ ghép
  { id: 716, type: 'chu-cai', upper: 'B', lower: 'b', words: ['ba', 'bé', 'bò', 'bạn'] },
  { id: 717, type: 'chu-cai', upper: 'C', lower: 'c', words: ['ca', 'cá', 'cô', 'cây'] },
  { id: 718, type: 'chu-cai', upper: 'E', lower: 'e', words: ['em', 'ếch', 'êm', 'én'] },
  { id: 719, type: 'on-tap', topic: 'Ôn tập chữ A B C E' },
  { id: 720, type: 'chu-cai', upper: 'O', lower: 'o', words: ['ô', 'ơ', 'ổi', 'ông'] },
  { id: 721, type: 'chu-cai', upper: 'Ô', lower: 'ô', words: ['ôm', 'ốc', 'ổn', 'ội'] },
  { id: 722, type: 'chu-cai', upper: 'D', lower: 'đ', words: ['da', 'đi', 'đọc', 'đèn'] },
  { id: 723, type: 'chu-cai', upper: 'Ơ', lower: 'ơ', words: ['ơi', 'ớt', 'ờ', 'ở'] },
  { id: 724, type: 'on-tap', topic: 'Ôn tập O Ô D Đ Ơ' },
  { id: 725, type: 'chu-cai', upper: 'I', lower: 'k', words: ['in', 'ít', 'kê', 'khi'] },
  { id: 726, type: 'chu-cai', upper: 'H', lower: 'l', words: ['hà', 'hoa', 'la', 'lá'] },
  { id: 727, type: 'chu-cai', upper: 'U', lower: 'ư', words: ['um', 'ưa', 'ưu', 'ước'] },
  { id: 728, type: 'chu-cai', upper: 'Ch', lower: 'kh', words: ['cha', 'chi', 'kho', 'khỉ'] },
  { id: 729, type: 'on-tap', topic: 'Ôn tập I K H L U Ư Ch Kh' },
  { id: 730, type: 'chu-cai', upper: 'M', lower: 'n', words: ['ma', 'mẹ', 'na', 'nụ'] },
  { id: 731, type: 'chu-cai', upper: 'G', lower: 'gi', words: ['ga', 'gà', 'gia', 'giọt'] },
  { id: 732, type: 'chu-cai', upper: 'Gh', lower: 'nh', words: ['ghế', 'ghi', 'nhà', 'nhỏ'] },
  { id: 733, type: 'chu-cai', upper: 'Ng', lower: 'ngh', words: ['nga', 'ngõ', 'nghĩ', 'nghe'] },
  { id: 734, type: 'on-tap', topic: 'Ôn tập M N G Gh Ng Ngh' },
  { id: 735, type: 'chu-cai', upper: 'R', lower: 's', words: ['ra', 'rổ', 'sa', 'sông'] },
  { id: 736, type: 'chu-cai', upper: 'T', lower: 'tr', words: ['ta', 'tô', 'trà', 'trẻ'] },
  { id: 737, type: 'chu-cai', upper: 'Th', lower: 'ia', words: ['thư', 'thơ', 'tia', 'bia'] },
  { id: 738, type: 'van', vanList: ['ua', 'ưa'], words: ['mua', 'dưa', 'cua', 'của'] },
  { id: 739, type: 'on-tap', topic: 'Ôn tập R S T Tr Th ia ua ưa' },
  { id: 740, type: 'chu-cai', upper: 'Ph', lower: 'qu', words: ['phố', 'phi', 'quả', 'quê'] },
  { id: 741, type: 'chu-cai', upper: 'V', lower: 'x', words: ['vở', 'vui', 'xa', 'xanh'] },
  { id: 742, type: 'chu-cai', upper: 'Y', lower: 'y', words: ['yêu', 'ý', 'yến', 'yêu'] },
  { id: 743, type: 'on-tap', topic: 'Luyện tập chính tả' },
  { id: 744, type: 'on-tap', topic: 'Ôn tập Ph Qu V X Y' },
  // Bài 31-80: Vần
  { id: 745, type: 'van', vanList: ['an', 'ân', 'ăn'], words: ['bàn', 'dân', 'bắn', 'đàn'] },
  { id: 746, type: 'van', vanList: ['on', 'ôn', 'ơn'], words: ['con', 'ôn', 'ơn', 'tôn'] },
  { id: 747, type: 'van', vanList: ['en', 'ên', 'in', 'un'], words: ['bên', 'nền', 'tin', 'mun'] },
  { id: 748, type: 'van', vanList: ['am', 'ăm', 'âm'], words: ['cam', 'tắm', 'âm', 'ham'] },
  { id: 749, type: 'on-tap', topic: 'Ôn tập vần an ân ăn on ôn ơn en ên in un am ăm âm' },
  { id: 750, type: 'van', vanList: ['om', 'ôm', 'ơm'], words: ['com', 'ôm', 'ơm', 'tôm'] },
  { id: 751, type: 'van', vanList: ['em', 'êm', 'im', 'um'], words: ['xem', 'êm', 'tim', 'um'] },
  { id: 752, type: 'van', vanList: ['ai', 'ay', 'ây'], words: ['hai', 'cây', 'dây', 'tai'] },
  { id: 753, type: 'van', vanList: ['oi', 'ôi', 'ơi'], words: ['gói', 'ôi', 'ơi', 'mồi'] },
  { id: 754, type: 'on-tap', topic: 'Ôn tập vần om ôm ơm em êm im um ai ay ây oi ôi ơi' },
  { id: 755, type: 'van', vanList: ['ui', 'ưi'], words: ['núi', 'gửi', 'tui', 'tủi'] },
  { id: 756, type: 'van', vanList: ['ao', 'eo'], words: ['cao', 'báo', 'leo', 'keo'] },
  { id: 757, type: 'van', vanList: ['au', 'âu', 'êu'], words: ['cau', 'đầu', 'bêu', 'màu'] },
  { id: 758, type: 'van', vanList: ['iu', 'ưu'], words: ['chiu', 'hưu', 'liu', 'lưu'] },
  { id: 759, type: 'on-tap', topic: 'Ôn tập vần ui ưi ao eo au âu êu iu ưu' },
  { id: 760, type: 'van', vanList: ['ac', 'ăc', 'âc'], words: ['bạc', 'bắc', 'đặc', 'mắc'] },
  { id: 761, type: 'van', vanList: ['oc', 'ôc', 'uc', 'ưc'], words: ['coc', 'óc', 'lúc', 'lực'] },
  { id: 762, type: 'van', vanList: ['at', 'ăt', 'ât'], words: ['bat', 'bắt', 'bật', 'mất'] },
  { id: 763, type: 'van', vanList: ['ot', 'ôt', 'ơt'], words: ['cot', 'ốt', 'ớt', 'tốt'] },
  { id: 764, type: 'on-tap', topic: 'Ôn tập vần ac ăc oc ôc uc at ăt ot ôt' },
  { id: 765, type: 'van', vanList: ['et', 'êt', 'it'], words: ['met', 'kết', 'mit', 'vit'] },
  { id: 766, type: 'van', vanList: ['ut', 'ưt'], words: ['but', 'bứt', 'hút', 'chứt'] },
  { id: 767, type: 'van', vanList: ['ap', 'ăp', 'âp'], words: ['gặp', 'cập', 'gap', 'tập'] },
  { id: 768, type: 'van', vanList: ['op', 'ôp', 'ơp'], words: ['hop', 'hộp', 'ốp', 'lớp'] },
  { id: 769, type: 'on-tap', topic: 'Ôn tập vần et êt it ut ưt ap ăp âp op ôp ơp' },
  { id: 770, type: 'van', vanList: ['ep', 'êp', 'ip', 'up'], words: ['đẹp', 'gặp', 'kíp', 'cup'] },
  { id: 771, type: 'van', vanList: ['anh', 'ênh', 'inh'], words: ['anh', 'bênh', 'bình', 'mình'] },
  { id: 772, type: 'van', vanList: ['ach', 'êch', 'ich'], words: ['ách', 'ếch', 'ích', 'dịch'] },
  { id: 773, type: 'van', vanList: ['ang', 'ăng', 'âng'], words: ['hang', 'hăng', 'nâng', 'cang'] },
  { id: 774, type: 'on-tap', topic: 'Ôn tập vần ep êp ip up anh ênh inh ach êch ang ăng' },
  { id: 775, type: 'van', vanList: ['ong', 'ông', 'ung', 'ưng'], words: ['cong', 'ông', 'rung', 'rừng'] },
  { id: 776, type: 'van', vanList: ['iêc', 'iên', 'iêp'], words: ['chiếc', 'tiên', 'tiếp', 'kiếp'] },
  { id: 777, type: 'van', vanList: ['iêng', 'iêm', 'yên'], words: ['tiếng', 'kiếm', 'yên', 'miền'] },
  { id: 778, type: 'van', vanList: ['iêt', 'iêu', 'yêu'], words: ['tiết', 'nhiều', 'yêu', 'chiều'] },
  { id: 779, type: 'on-tap', topic: 'Ôn tập vần ong ông ung ưng iêc iên iêp iêng yên' },
  { id: 780, type: 'van', vanList: ['uôi', 'uôm'], words: ['muối', 'buồm', 'tuổi', 'cuộm'] },
  { id: 781, type: 'van', vanList: ['uôc', 'uôt'], words: ['thuốc', 'buộc', 'muốt', 'tuột'] },
  { id: 782, type: 'van', vanList: ['uôn', 'uông'], words: ['buồn', 'muốn', 'buông', 'ruộng'] },
  { id: 783, type: 'van', vanList: ['ươi', 'ươu'], words: ['mươi', 'bướu', 'tươi', 'rượu'] },
  { id: 784, type: 'on-tap', topic: 'Ôn tập vần uôi uôm uôc uôt uôn uông ươi ươu' },
  { id: 785, type: 'van', vanList: ['ước', 'ướt'], words: ['bước', 'ước', 'bướt', 'lướt'] },
  { id: 786, type: 'van', vanList: ['ươm', 'ươp'], words: ['bướm', 'ướm', 'lướp', 'tướp'] },
  { id: 787, type: 'van', vanList: ['ươn', 'ương'], words: ['hương', 'đường', 'vươn', 'nương'] },
  { id: 788, type: 'van', vanList: ['oa', 'oe'], words: ['hoa', 'toa', 'khoe', 'ngoè'] },
  { id: 789, type: 'on-tap', topic: 'Ôn tập vần ước ướt ươm ươp ươn ương oa oe' },
  { id: 790, type: 'van', vanList: ['oan', 'oăn', 'oat', 'oăt'], words: ['loan', 'xoăn', 'ngoạt', 'hoặt'] },
  { id: 791, type: 'van', vanList: ['oai', 'uê', 'uy'], words: ['ngoài', 'huệ', 'tuy', 'quý'] },
  { id: 792, type: 'van', vanList: ['uân', 'uât'], words: ['xuân', 'tuần', 'xuất', 'thuật'] },
  { id: 793, type: 'van', vanList: ['uyên', 'uyêt'], words: ['quyên', 'tuyên', 'tuyệt', 'quyết'] },
  { id: 794, type: 'on-tap', topic: 'Ôn tập vần oan oai uê uy uân uât uyên uyêt' },
  // Tập 2: Đọc hiểu
  { id: 795, type: 'doc-hieu', story: 'Tôi là học sinh lớp 1', topic: 'trường học' },
  { id: 796, type: 'doc-hieu', story: 'Đôi tai xấu xí', topic: 'tình bạn' },
  { id: 797, type: 'doc-hieu', story: 'Bạn của gió', topic: 'thiên nhiên' },
  { id: 798, type: 'doc-hieu', story: 'Giải thưởng tình bạn', topic: 'tình bạn' },
  { id: 799, type: 'doc-hieu', story: 'Sinh nhật của voi con', topic: 'sinh nhật' },
  { id: 800, type: 'on-tap', topic: 'Ôn tập Chủ đề 1 - Trường học và tình bạn' },
  { id: 801, type: 'doc-hieu', story: 'Nụ hôn trên bàn tay', topic: 'gia đình' },
  { id: 802, type: 'doc-hieu', story: 'Làm anh', topic: 'gia đình' },
  { id: 803, type: 'doc-hieu', story: 'Cả nhà đi chơi núi', topic: 'gia đình' },
  { id: 804, type: 'doc-hieu', story: 'Quạt cho bà ngủ', topic: 'gia đình' },
  { id: 805, type: 'doc-hieu', story: 'Bữa cơm gia đình', topic: 'gia đình' },
  { id: 806, type: 'doc-hieu', story: 'Ngôi nhà', topic: 'gia đình' },
  { id: 807, type: 'on-tap', topic: 'Ôn tập Chủ đề 2 - Gia đình' },
  { id: 808, type: 'doc-hieu', story: 'Tôi đi học', topic: 'trường học' },
  { id: 809, type: 'doc-hieu', story: 'Đi học', topic: 'trường học' },
  { id: 810, type: 'doc-hieu', story: 'Hoa yêu thương', topic: 'trường học' },
  { id: 811, type: 'doc-hieu', story: 'Cây bàng và lớp học', topic: 'trường học' },
  { id: 812, type: 'doc-hieu', story: 'Bác trống trường', topic: 'trường học' },
  { id: 813, type: 'doc-hieu', story: 'Giờ ra chơi', topic: 'trường học' },
  { id: 814, type: 'on-tap', topic: 'Ôn tập Chủ đề 3 - Trường học' },
  { id: 815, type: 'doc-hieu', story: 'Rửa tay trước khi ăn', topic: 'sức khỏe' },
  { id: 816, type: 'doc-hieu', story: 'Lời chào', topic: 'phép lịch sự' },
  { id: 817, type: 'doc-hieu', story: 'Khi mẹ vắng nhà', topic: 'gia đình' },
  { id: 818, type: 'doc-hieu', story: 'Nếu không may bị lạc', topic: 'an toàn' },
  { id: 819, type: 'doc-hieu', story: 'Đèn giao thông', topic: 'an toàn' },
  { id: 820, type: 'on-tap', topic: 'Ôn tập Chủ đề 4 - An toàn và sức khỏe' },
  { id: 821, type: 'doc-hieu', story: 'Kiến và chim bồ câu', topic: 'đạo đức' },
  { id: 822, type: 'doc-hieu', story: 'Câu chuyện của rễ', topic: 'thiên nhiên' },
  { id: 823, type: 'doc-hieu', story: 'Câu hỏi của sói', topic: 'đạo đức' },
  { id: 824, type: 'doc-hieu', story: 'Chú bé chăn cừu', topic: 'đạo đức' },
  { id: 825, type: 'doc-hieu', story: 'Tiếng vọng của núi', topic: 'đạo đức' },
  { id: 826, type: 'on-tap', topic: 'Ôn tập Chủ đề 5 - Đạo đức và bài học' },
  { id: 827, type: 'doc-hieu', story: 'Loài chim của biển cả', topic: 'thiên nhiên' },
  { id: 828, type: 'doc-hieu', story: 'Bảy sắc cầu vồng', topic: 'thiên nhiên' },
  { id: 829, type: 'doc-hieu', story: 'Chúa tể rừng xanh', topic: 'thiên nhiên' },
  { id: 830, type: 'doc-hieu', story: 'Cuộc thi tài năng rừng xanh', topic: 'thiên nhiên' },
  { id: 831, type: 'doc-hieu', story: 'Cây liễu dẻo dai', topic: 'thiên nhiên' },
  { id: 832, type: 'on-tap', topic: 'Ôn tập Chủ đề 6 - Thiên nhiên' },
  { id: 833, type: 'doc-hieu', story: 'Tia nắng đi đâu', topic: 'thiên nhiên' },
  { id: 834, type: 'doc-hieu', story: 'Trong giấc mơ buổi sáng', topic: 'cuộc sống' },
  { id: 835, type: 'doc-hieu', story: 'Ngày mới bắt đầu', topic: 'cuộc sống' },
  { id: 836, type: 'doc-hieu', story: 'Hỏi mẹ', topic: 'gia đình' },
  { id: 837, type: 'doc-hieu', story: 'Những cánh cò', topic: 'thiên nhiên' },
  { id: 838, type: 'doc-hieu', story: 'Buổi trưa hè', topic: 'cuộc sống' },
  { id: 839, type: 'doc-hieu', story: 'Hoa phượng', topic: 'thiên nhiên' },
  { id: 840, type: 'on-tap', topic: 'Ôn tập Chủ đề 7 - Cuộc sống và thiên nhiên' },
  { id: 841, type: 'doc-hieu', story: 'Cậu bé thông minh', topic: 'cuộc sống' },
  { id: 842, type: 'doc-hieu', story: 'Lính cứu hỏa', topic: 'nghề nghiệp' },
  { id: 843, type: 'doc-hieu', story: 'Lớn lên bạn làm gì?', topic: 'nghề nghiệp' },
  { id: 844, type: 'doc-hieu', story: 'Ruộng bậc thang ở Sa Pa', topic: 'đất nước' },
  { id: 845, type: 'doc-hieu', story: 'Nhớ ơn', topic: 'đạo đức' },
  { id: 846, type: 'doc-hieu', story: 'Du lịch biển Việt Nam', topic: 'đất nước' },
  { id: 847, type: 'on-tap', topic: 'Ôn tập Chủ đề 8 - Nghề nghiệp và đất nước' },
  { id: 848, type: 'on-tap', topic: 'Ôn tập và đánh giá tổng hợp 1' },
  { id: 849, type: 'on-tap', topic: 'Ôn tập và đánh giá tổng hợp 2' },
  { id: 850, type: 'on-tap', topic: 'Ôn tập và đánh giá tổng hợp 3' },
];

// ─── Question generators ──────────────────────────────────────────────────────

function makeChuCaiQuizzes(l: ChuCaiLesson): QuizSeed[] {
  const U = l.upper, Lo = l.lower;
  const [w1, w2, w3, w4] = l.words;
  const notWords = ['gấu', 'hồ', 'núi', 'sao'].filter(w => !l.words.includes(w));
  return [
    // Bài tập 1: Nhận biết (easy)
    { exerciseNumber: 1, sortOrder: 1, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Đây là chữ gì? "${U}"`,
      optionsJson: [{ key: 'A', text: U }, { key: 'B', text: 'H' }, { key: 'C', text: 'K' }, { key: 'D', text: 'M' }],
      correctAnswerJson: 'A', explanation: `Đây là chữ ${U}.` },
    { exerciseNumber: 1, sortOrder: 2, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Chữ "${Lo}" và chữ "${U}" là cùng một chữ cái`,
      correctAnswerJson: true, explanation: `"${Lo}" là chữ thường, "${U}" là chữ hoa của cùng một chữ.` },
    { exerciseNumber: 1, sortOrder: 3, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Từ nào bắt đầu bằng chữ ${U}?`,
      optionsJson: [{ key: 'A', text: w1 }, { key: 'B', text: 'tôm' }, { key: 'C', text: 'quả' }, { key: 'D', text: 'dê' }],
      correctAnswerJson: 'A', explanation: `"${w1}" bắt đầu bằng chữ ${Lo}.` },
    { exerciseNumber: 1, sortOrder: 4, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Chữ hoa của "${Lo}" là gì?`,
      optionsJson: [{ key: 'A', text: U }, { key: 'B', text: 'T' }, { key: 'C', text: 'P' }, { key: 'D', text: 'S' }],
      correctAnswerJson: 'A', explanation: `Chữ hoa của "${Lo}" là "${U}".` },
    { exerciseNumber: 1, sortOrder: 5, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Từ "${w2}" có chứa chữ "${Lo}"`,
      correctAnswerJson: true, explanation: `"${w2}" có chứa chữ "${Lo}".` },
    { exerciseNumber: 1, sortOrder: 6, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Từ nào có chữ "${Lo}"?`,
      optionsJson: [{ key: 'A', text: w3 }, { key: 'B', text: notWords[0] }, { key: 'C', text: notWords[1] }, { key: 'D', text: notWords[2] }],
      correctAnswerJson: 'A', explanation: `"${w3}" có chứa chữ "${Lo}".` },
    { exerciseNumber: 1, sortOrder: 7, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Chữ thường của "${U}" là gì?`,
      optionsJson: [{ key: 'A', text: Lo }, { key: 'B', text: 'p' }, { key: 'C', text: 'q' }, { key: 'D', text: 'r' }],
      correctAnswerJson: 'A', explanation: `Chữ thường của "${U}" là "${Lo}".` },
    { exerciseNumber: 1, sortOrder: 8, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Chữ "${U}" là một chữ cái trong bảng chữ cái tiếng Việt`,
      correctAnswerJson: true, explanation: `Đúng, "${U}" là chữ cái trong bảng chữ cái tiếng Việt.` },
    { exerciseNumber: 1, sortOrder: 9, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Từ nào KHÔNG có chữ "${Lo}"?`,
      optionsJson: [{ key: 'A', text: notWords[0] }, { key: 'B', text: w1 }, { key: 'C', text: w2 }, { key: 'D', text: w3 }],
      correctAnswerJson: 'A', explanation: `"${notWords[0]}" không chứa chữ "${Lo}".` },
    { exerciseNumber: 1, sortOrder: 10, difficultyLevel: 'easy', questionType: 'matching',
      questionText: `Nối chữ hoa với chữ thường tương ứng`,
      optionsJson: [{ key: 'P1', text: U }, { key: 'P2', text: 'M' }, { key: 'P3', text: 'T' }],
      correctAnswerJson: { P1: Lo, P2: 'm', P3: 't' }, explanation: `${U}-${Lo}, M-m, T-t.` },
    // Bài tập 2: Đọc và ghép (medium)
    { exerciseNumber: 2, sortOrder: 1, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Từ "${w1}" có mấy chữ cái?`,
      optionsJson: [{ key: 'A', text: String(w1.length) }, { key: 'B', text: String(w1.length + 1) }, { key: 'C', text: '1' }, { key: 'D', text: '5' }],
      correctAnswerJson: 'A', explanation: `"${w1}" có ${w1.length} chữ cái.` },
    { exerciseNumber: 2, sortOrder: 2, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: `Sắp xếp các chữ cái để tạo thành từ "${w2}"`,
      optionsJson: w2.split('').map((c, i) => ({ key: String(i + 1), text: c })),
      correctAnswerJson: w2.split('').map((_, i) => String(i + 1)), explanation: `Xếp theo thứ tự tạo thành "${w2}".` },
    { exerciseNumber: 2, sortOrder: 3, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Chữ "${Lo}" đứng ở vị trí nào trong từ "${w1}"?`,
      optionsJson: [{ key: 'A', text: 'Đầu' }, { key: 'B', text: 'Giữa' }, { key: 'C', text: 'Cuối' }],
      correctAnswerJson: w1.indexOf(Lo) === 0 ? 'A' : (w1.indexOf(Lo) === w1.length - 1 ? 'C' : 'B'),
      explanation: `Trong "${w1}", chữ "${Lo}" đứng ở ${w1.indexOf(Lo) === 0 ? 'đầu' : w1.indexOf(Lo) === w1.length - 1 ? 'cuối' : 'giữa'}.` },
    { exerciseNumber: 2, sortOrder: 4, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: `Chữ "${Lo}" và chữ "p" phát âm giống nhau`,
      correctAnswerJson: false, explanation: `"${Lo}" và "p" là hai chữ cái khác nhau, phát âm khác nhau.` },
    { exerciseNumber: 2, sortOrder: 5, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Từ nào có nghĩa là "${w3}"?`,
      optionsJson: [{ key: 'A', text: w3 }, { key: 'B', text: w4 }, { key: 'C', text: notWords[0] }, { key: 'D', text: notWords[1] }],
      correctAnswerJson: 'A', explanation: `"${w3}" là từ đúng.` },
    { exerciseNumber: 2, sortOrder: 6, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Ghép "${Lo}" với âm để được từ "${w1}"`,
      optionsJson: [{ key: 'A', text: w1 }, { key: 'B', text: w2 }, { key: 'C', text: w3 }, { key: 'D', text: w4 }],
      correctAnswerJson: 'A', explanation: `Đáp án đúng là "${w1}".` },
    { exerciseNumber: 2, sortOrder: 7, difficultyLevel: 'medium', questionType: 'matching',
      questionText: `Nối chữ cái với từ chứa chữ đó`,
      optionsJson: [{ key: 'P1', text: U }, { key: 'P2', text: 'H' }, { key: 'P3', text: 'L' }],
      correctAnswerJson: { P1: w1, P2: 'hoa', P3: 'lá' },
      explanation: `${U}-${w1}, H-hoa, L-lá.` },
    { exerciseNumber: 2, sortOrder: 8, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Điền chữ còn thiếu để được từ "${w4}": "_${w4.slice(1)}"`,
      optionsJson: [{ key: 'A', text: w4[0] }, { key: 'B', text: 'z' }, { key: 'C', text: 'x' }, { key: 'D', text: 'q' }],
      correctAnswerJson: 'A', explanation: `${w4[0]} + ${w4.slice(1)} = ${w4}.` },
    { exerciseNumber: 2, sortOrder: 9, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: `Sắp xếp các chữ cái để tạo thành từ "${w3}"`,
      optionsJson: w3.split('').map((c, i) => ({ key: String(i + 1), text: c })),
      correctAnswerJson: w3.split('').map((_, i) => String(i + 1)), explanation: `Xếp theo thứ tự tạo thành "${w3}".` },
    { exerciseNumber: 2, sortOrder: 10, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: `Từ "${w1}" và từ "${w2}" đều có chữ "${Lo}"`,
      correctAnswerJson: w1.includes(Lo) && w2.includes(Lo),
      explanation: `${w1.includes(Lo) ? `"${w1}"` : ''} ${w2.includes(Lo) ? `và "${w2}"` : ''} có chứa chữ "${Lo}".` },
    // Bài tập 3: Vận dụng (hard)
    { exerciseNumber: 3, sortOrder: 1, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Câu nào có nhiều chữ "${Lo}" nhất?`,
      optionsJson: [{ key: 'A', text: `${w1} và ${w2}` }, { key: 'B', text: 'mèo ngủ ngon' }, { key: 'C', text: 'hoa nở sớm' }, { key: 'D', text: 'chim hót hay' }],
      correctAnswerJson: 'A', explanation: `"${w1} và ${w2}" có nhiều chữ "${Lo}" nhất.` },
    { exerciseNumber: 3, sortOrder: 2, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `"${w1}" và "${w2}" khác nhau ở chỗ nào?`,
      optionsJson: [{ key: 'A', text: 'Chữ cái' }, { key: 'B', text: 'Dấu thanh' }, { key: 'C', text: 'Không khác' }, { key: 'D', text: 'Số âm tiết' }],
      correctAnswerJson: w1 === w2 ? 'C' : (w1.replace(/[àáảãạăắặẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđ]/g, 'x') === w2.replace(/[àáảãạăắặẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđ]/g, 'x') ? 'B' : 'A'),
      explanation: `"${w1}" và "${w2}" khác nhau về chữ cái hoặc dấu thanh.` },
    { exerciseNumber: 3, sortOrder: 3, difficultyLevel: 'hard', questionType: 'matching',
      questionText: `Nối từ với âm đầu của nó`,
      optionsJson: [{ key: 'P1', text: w1 }, { key: 'P2', text: w2 }, { key: 'P3', text: w3 }],
      correctAnswerJson: { P1: w1[0], P2: w2[0], P3: w3[0] },
      explanation: `${w1} bắt đầu bằng "${w1[0]}", ${w2} bắt đầu bằng "${w2[0]}", ${w3} bắt đầu bằng "${w3[0]}".` },
    { exerciseNumber: 3, sortOrder: 4, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Điền vào chỗ trống: "Con ___ đang bay"`,
      optionsJson: [{ key: 'A', text: w2 }, { key: 'B', text: 'đá' }, { key: 'C', text: 'nhà' }, { key: 'D', text: 'bàn' }],
      correctAnswerJson: 'A', explanation: `"${w2}" phù hợp với ngữ cảnh câu.` },
    { exerciseNumber: 3, sortOrder: 5, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: `Chữ "${U}" là chữ nguyên âm`,
      correctAnswerJson: ['A', 'E', 'I', 'O', 'U', 'Ô', 'Ơ', 'Ê', 'Ư'].includes(U),
      explanation: `"${U}" ${['A', 'E', 'I', 'O', 'U', 'Ô', 'Ơ', 'Ê', 'Ư'].includes(U) ? 'là' : 'không phải là'} chữ nguyên âm.` },
    { exerciseNumber: 3, sortOrder: 6, difficultyLevel: 'hard', questionType: 'drag_drop',
      questionText: `Sắp xếp thành câu có nghĩa`,
      optionsJson: [{ key: '1', text: w1 }, { key: '2', text: 'và' }, { key: '3', text: w2 }],
      correctAnswerJson: ['1', '2', '3'], explanation: `"${w1} và ${w2}" là cách xếp hợp lý.` },
    { exerciseNumber: 3, sortOrder: 7, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Chữ "${Lo}" xuất hiện mấy lần trong cụm "${w1} ${w2} ${w3}"?`,
      optionsJson: [{ key: 'A', text: String((`${w1} ${w2} ${w3}`).split(Lo).length - 1) }, { key: 'B', text: '0' }, { key: 'C', text: '10' }, { key: 'D', text: '5' }],
      correctAnswerJson: 'A', explanation: `Chữ "${Lo}" xuất hiện ${(`${w1} ${w2} ${w3}`).split(Lo).length - 1} lần.` },
    { exerciseNumber: 3, sortOrder: 8, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Từ nào dùng được trong câu "Mẹ mua ___ về"?`,
      optionsJson: [{ key: 'A', text: w4 }, { key: 'B', text: U }, { key: 'C', text: Lo }, { key: 'D', text: '123' }],
      correctAnswerJson: 'A', explanation: `"${w4}" là từ có thể dùng trong câu đó.` },
    { exerciseNumber: 3, sortOrder: 9, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: `Bảng chữ cái tiếng Việt có 29 chữ cái`,
      correctAnswerJson: true, explanation: `Bảng chữ cái tiếng Việt có 29 chữ cái.` },
    { exerciseNumber: 3, sortOrder: 10, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Câu nào dùng đúng từ có chữ "${Lo}"?`,
      optionsJson: [{ key: 'A', text: `${w1} của em đẹp lắm` }, { key: 'B', text: 'Trời mưa to' }, { key: 'C', text: 'Hoa nở vàng' }, { key: 'D', text: 'Ngày mới sang' }],
      correctAnswerJson: 'A', explanation: `"${w1} của em đẹp lắm" dùng từ có chữ "${Lo}".` },
  ];
}

function makeVanQuizzes(l: VanLesson): QuizSeed[] {
  const vanStr = l.vanList.join(', ');
  const [v1, v2] = l.vanList;
  const [w1, w2, w3, w4] = l.words;
  // Build unique word→vần pairs for matching (avoid duplicate right-side values)
  const vanPairs: { key: string; word: string; van: string }[] = [];
  const usedVan = new Set<string>();
  l.vanList.forEach((v, i) => {
    if (!usedVan.has(v) && l.words[i]) { vanPairs.push({ key: `VP${i+1}`, word: l.words[i], van: v }); usedVan.add(v); }
  });
  const vp = vanPairs.slice(0, 3);
  return [
    // Bài tập 1: Nhận biết vần (easy)
    { exerciseNumber: 1, sortOrder: 1, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Từ "${w1}" có vần gì?`,
      optionsJson: [{ key: 'A', text: v1 }, { key: 'B', text: 'at' }, { key: 'C', text: 'oa' }, { key: 'D', text: 'uy' }],
      correctAnswerJson: 'A', explanation: `"${w1}" có vần "${v1}".` },
    { exerciseNumber: 1, sortOrder: 2, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Vần "${v1}" và vần "${v2 ?? v1}" giống nhau hoàn toàn`,
      correctAnswerJson: v1 === v2, explanation: `"${v1}" và "${v2 ?? v1}" ${v1 === v2 ? 'giống nhau' : 'khác nhau'}.` },
    { exerciseNumber: 1, sortOrder: 3, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Từ nào có vần "${v1}"?`,
      optionsJson: [{ key: 'A', text: w1 }, { key: 'B', text: 'phố' }, { key: 'C', text: 'quê' }, { key: 'D', text: 'sơn' }],
      correctAnswerJson: 'A', explanation: `"${w1}" có vần "${v1}".` },
    { exerciseNumber: 1, sortOrder: 4, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `"${w2}" có vần "${v1}"`,
      correctAnswerJson: w2.endsWith(v1) || w2.includes(v1),
      explanation: `"${w2}" ${w2.includes(v1) ? 'có' : 'không có'} vần "${v1}".` },
    { exerciseNumber: 1, sortOrder: 5, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Bài học hôm nay học vần gì?`,
      optionsJson: [{ key: 'A', text: vanStr }, { key: 'B', text: 'oa, oe' }, { key: 'C', text: 'uy, uê' }, { key: 'D', text: 'in, un' }],
      correctAnswerJson: 'A', explanation: `Bài học vần ${vanStr}.` },
    { exerciseNumber: 1, sortOrder: 6, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Từ nào có vần "${v2 ?? v1}"?`,
      optionsJson: [{ key: 'A', text: w3 }, { key: 'B', text: 'tôi' }, { key: 'C', text: 'bạn' }, { key: 'D', text: 'sách' }],
      correctAnswerJson: 'A', explanation: `"${w3}" có vần liên quan đến bài học.` },
    { exerciseNumber: 1, sortOrder: 7, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Vần "${v1}" có trong từ "${w1}"`,
      correctAnswerJson: w1.includes(v1.replace(/[àáảãạăắặẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵ]/g, c => c)),
      explanation: `"${w1}" ${w1.includes(v1) ? 'có' : 'chứa'} vần "${v1}".` },
    { exerciseNumber: 1, sortOrder: 8, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `"${w4}" thuộc nhóm vần nào trong bài?`,
      optionsJson: [{ key: 'A', text: vanStr }, { key: 'B', text: 'oa oe' }, { key: 'C', text: 'uê uy' }, { key: 'D', text: 'an ân' }],
      correctAnswerJson: 'A', explanation: `"${w4}" thuộc nhóm vần ${vanStr}.` },
    { exerciseNumber: 1, sortOrder: 9, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Vần là phần còn lại của tiếng sau khi bỏ âm đầu`,
      correctAnswerJson: true, explanation: `Đúng, vần là phần gồm âm chính và âm cuối của tiếng.` },
    { exerciseNumber: 1, sortOrder: 10, difficultyLevel: 'easy', questionType: 'matching',
      questionText: `Nối từ với vần của nó`,
      optionsJson: vp.map(p => ({ key: p.key, text: p.word })),
      correctAnswerJson: Object.fromEntries(vp.map(p => [p.key, p.van])),
      explanation: vp.map(p => `${p.word}→${p.van}`).join(', ') + '.' },
    // Bài tập 2: Đọc, ghép vần (medium)
    { exerciseNumber: 2, sortOrder: 1, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Ghép âm đầu "b" với vần "${v1}" được tiếng gì?`,
      optionsJson: [{ key: 'A', text: `b${v1}` }, { key: 'B', text: 'bê' }, { key: 'C', text: 'bơ' }, { key: 'D', text: 'bi' }],
      correctAnswerJson: 'A', explanation: `b + ${v1} = b${v1}.` },
    { exerciseNumber: 2, sortOrder: 2, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: `Sắp xếp để tạo thành từ "${w1}"`,
      optionsJson: w1.split('').map((c, i) => ({ key: String(i + 1), text: c })),
      correctAnswerJson: w1.split('').map((_, i) => String(i + 1)), explanation: `Xếp theo thứ tự tạo thành "${w1}".` },
    { exerciseNumber: 2, sortOrder: 3, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Từ "${w2}" đọc như thế nào?`,
      optionsJson: [{ key: 'A', text: w2 }, { key: 'B', text: w3 }, { key: 'C', text: w4 }, { key: 'D', text: w1 }],
      correctAnswerJson: 'A', explanation: `Cách đọc đúng là "${w2}".` },
    { exerciseNumber: 2, sortOrder: 4, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: `"${w1}" và "${w3}" cùng vần`,
      correctAnswerJson: false, explanation: `"${w1}" và "${w3}" có thể khác vần.` },
    { exerciseNumber: 2, sortOrder: 5, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Tìm từ có vần "${v1}" trong câu "Bé ${w1} với ${w2}"`,
      optionsJson: [{ key: 'A', text: w1 }, { key: 'B', text: 'Bé' }, { key: 'C', text: 'với' }, { key: 'D', text: 'và' }],
      correctAnswerJson: 'A', explanation: `"${w1}" có vần "${v1}".` },
    { exerciseNumber: 2, sortOrder: 6, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Điền vần thích hợp: "b___" để được từ "${w1}"`,
      optionsJson: [{ key: 'A', text: w1.slice(1) }, { key: 'B', text: 'oa' }, { key: 'C', text: 'uy' }, { key: 'D', text: 'an' }],
      correctAnswerJson: 'A', explanation: `b + ${w1.slice(1)} = ${w1}.` },
    { exerciseNumber: 2, sortOrder: 7, difficultyLevel: 'medium', questionType: 'matching',
      questionText: `Nối tiếng với vần tương ứng`,
      optionsJson: vp.map(p => ({ key: p.key, text: p.word })),
      correctAnswerJson: Object.fromEntries(vp.map(p => [p.key, p.van])),
      explanation: vp.map(p => `${p.word}→${p.van}`).join(', ') + '.' },
    { exerciseNumber: 2, sortOrder: 8, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Từ nào ghép đúng từ âm "t" và vần "${v1}"?`,
      optionsJson: [{ key: 'A', text: `t${v1}` }, { key: 'B', text: 'toa' }, { key: 'C', text: 'tuy' }, { key: 'D', text: 'tin' }],
      correctAnswerJson: 'A', explanation: `t + ${v1} = t${v1}.` },
    { exerciseNumber: 2, sortOrder: 9, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: `Sắp xếp để tạo thành từ "${w3}"`,
      optionsJson: w3.split('').map((c, i) => ({ key: String(i + 1), text: c })),
      correctAnswerJson: w3.split('').map((_, i) => String(i + 1)), explanation: `Xếp theo thứ tự tạo thành "${w3}".` },
    { exerciseNumber: 2, sortOrder: 10, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: `Vần "${v1}" có thể ghép với nhiều âm đầu khác nhau`,
      correctAnswerJson: true, explanation: `Đúng, vần "${v1}" có thể ghép với b, c, d, m, n, t... để tạo nhiều tiếng.` },
    // Bài tập 3: Vận dụng (hard)
    { exerciseNumber: 3, sortOrder: 1, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Câu nào có nhiều từ vần "${v1}" nhất?`,
      optionsJson: [{ key: 'A', text: `${w1} và ${w2}` }, { key: 'B', text: 'Hoa thơm ngát' }, { key: 'C', text: 'Trời xanh cao' }, { key: 'D', text: 'Mây trắng bay' }],
      correctAnswerJson: 'A', explanation: `"${w1} và ${w2}" có nhiều từ vần "${v1}" nhất.` },
    { exerciseNumber: 3, sortOrder: 2, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `"${v1}" và "${v2 ?? 'an'}" khác nhau ở điểm nào?`,
      optionsJson: [{ key: 'A', text: 'Nguyên âm chính' }, { key: 'B', text: 'Âm cuối' }, { key: 'C', text: 'Không khác' }, { key: 'D', text: 'Dấu thanh' }],
      correctAnswerJson: 'A', explanation: `"${v1}" và "${v2 ?? 'an'}" khác nhau ở nguyên âm chính hoặc âm cuối.` },
    { exerciseNumber: 3, sortOrder: 3, difficultyLevel: 'hard', questionType: 'matching',
      questionText: `Nối tiếng với vần tương ứng`,
      optionsJson: vp.map(p => ({ key: p.key, text: p.word })),
      correctAnswerJson: Object.fromEntries(vp.map(p => [p.key, p.van])),
      explanation: vp.map(p => `${p.word}→${p.van}`).join(', ') + '.' },
    { exerciseNumber: 3, sortOrder: 4, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Điền vào chỗ trống: "Em ___ sách rất hay"`,
      optionsJson: [{ key: 'A', text: w1 }, { key: 'B', text: 'oa' }, { key: 'C', text: 'uy' }, { key: 'D', text: 'abc' }],
      correctAnswerJson: 'A', explanation: `"${w1}" phù hợp với ngữ cảnh.` },
    { exerciseNumber: 3, sortOrder: 5, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: `Vần "${v1}" xuất hiện trong từ "${w4}"`,
      correctAnswerJson: w4.includes(v1.slice(-2)) || w4.includes(v1),
      explanation: `"${w4}" ${w4.includes(v1) ? 'có' : 'không có chính xác'} vần "${v1}".` },
    { exerciseNumber: 3, sortOrder: 6, difficultyLevel: 'hard', questionType: 'drag_drop',
      questionText: `Sắp xếp thành câu: "${w1} của em rất ${w2}"`,
      optionsJson: [{ key: '1', text: w1 }, { key: '2', text: 'của' }, { key: '3', text: 'em' }, { key: '4', text: 'rất' }, { key: '5', text: w2 }],
      correctAnswerJson: ['1', '2', '3', '4', '5'], explanation: `Câu đúng: "${w1} của em rất ${w2}".` },
    { exerciseNumber: 3, sortOrder: 7, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Trong nhóm vần "${vanStr}", vần nào có âm cuối "n"?`,
      optionsJson: [{ key: 'A', text: l.vanList.find(v => v.endsWith('n')) ?? v1 }, { key: 'B', text: 'oa' }, { key: 'C', text: 'uy' }, { key: 'D', text: 'ac' }],
      correctAnswerJson: 'A', explanation: `Vần kết thúc bằng "n" trong nhóm này.` },
    { exerciseNumber: 3, sortOrder: 8, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Từ nào dùng được trong câu "Bé thích ăn ___"?`,
      optionsJson: [{ key: 'A', text: w3 }, { key: 'B', text: 'bầu trời' }, { key: 'C', text: 'ngọn núi' }, { key: 'D', text: 'con đường' }],
      correctAnswerJson: 'A', explanation: `"${w3}" phù hợp với ngữ cảnh ăn uống.` },
    { exerciseNumber: 3, sortOrder: 9, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: `Tiếng Việt có nhiều vần hơn tiếng Anh`,
      correctAnswerJson: true, explanation: `Tiếng Việt có hơn 100 vần khác nhau, nhiều hơn tiếng Anh.` },
    { exerciseNumber: 3, sortOrder: 10, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Câu nào viết đúng chính tả với vần "${v1}"?`,
      optionsJson: [{ key: 'A', text: `Mẹ mua ${w1} về.` }, { key: 'B', text: 'Bạn ơi chờ tôi.' }, { key: 'C', text: 'Trời mưa to lắm.' }, { key: 'D', text: 'Cây xanh ngát.' }],
      correctAnswerJson: 'A', explanation: `"Mẹ mua ${w1} về." dùng từ có vần "${v1}" đúng chính tả.` },
  ];
}

function makeOnTapQuizzes(l: OnTapLesson): QuizSeed[] {
  const topic = l.topic;
  return [
    { exerciseNumber: 1, sortOrder: 1, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Bài học ôn tập hôm nay về chủ đề gì?`,
      optionsJson: [{ key: 'A', text: topic }, { key: 'B', text: 'Toán học' }, { key: 'C', text: 'Khoa học' }, { key: 'D', text: 'Mỹ thuật' }],
      correctAnswerJson: 'A', explanation: `Bài ôn tập về: ${topic}.` },
    { exerciseNumber: 1, sortOrder: 2, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: 'Ôn tập giúp chúng ta nhớ bài lâu hơn',
      correctAnswerJson: true, explanation: 'Ôn tập thường xuyên giúp ghi nhớ tốt hơn.' },
    { exerciseNumber: 1, sortOrder: 3, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: 'Khi ôn tập, ta nên làm gì?',
      optionsJson: [{ key: 'A', text: 'Đọc lại bài và làm bài tập' }, { key: 'B', text: 'Xem phim' }, { key: 'C', text: 'Ngủ ngay' }, { key: 'D', text: 'Chơi game' }],
      correctAnswerJson: 'A', explanation: 'Đọc lại và làm bài tập là cách ôn tập hiệu quả.' },
    { exerciseNumber: 1, sortOrder: 4, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: 'Bảng chữ cái tiếng Việt có 29 chữ cái',
      correctAnswerJson: true, explanation: 'Bảng chữ cái tiếng Việt có đúng 29 chữ cái.' },
    { exerciseNumber: 1, sortOrder: 5, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: 'Tiếng Việt có bao nhiêu dấu thanh?',
      optionsJson: [{ key: 'A', text: '6' }, { key: 'B', text: '4' }, { key: 'C', text: '5' }, { key: 'D', text: '7' }],
      correctAnswerJson: 'A', explanation: 'Tiếng Việt có 6 dấu thanh: ngang, huyền, sắc, hỏi, ngã, nặng.' },
    { exerciseNumber: 1, sortOrder: 6, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: 'Dấu hỏi (?) dùng ở cuối câu hỏi',
      correctAnswerJson: true, explanation: 'Dấu chấm hỏi dùng ở cuối câu hỏi.' },
    { exerciseNumber: 1, sortOrder: 7, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: 'Chữ nào là chữ nguyên âm?',
      optionsJson: [{ key: 'A', text: 'A' }, { key: 'B', text: 'B' }, { key: 'C', text: 'C' }, { key: 'D', text: 'D' }],
      correctAnswerJson: 'A', explanation: '"A" là nguyên âm, B C D là phụ âm.' },
    { exerciseNumber: 1, sortOrder: 8, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: 'Mỗi tiếng trong tiếng Việt đều có vần',
      correctAnswerJson: true, explanation: 'Mỗi tiếng đều có phần vần (âm chính).' },
    { exerciseNumber: 1, sortOrder: 9, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: 'Câu "Bé đi học." có bao nhiêu tiếng?',
      optionsJson: [{ key: 'A', text: '3' }, { key: 'B', text: '2' }, { key: 'C', text: '4' }, { key: 'D', text: '5' }],
      correctAnswerJson: 'A', explanation: '"Bé đi học" có 3 tiếng.' },
    { exerciseNumber: 1, sortOrder: 10, difficultyLevel: 'easy', questionType: 'matching',
      questionText: 'Nối chữ hoa với chữ thường',
      optionsJson: [{ key: 'A', text: 'A' }, { key: 'B', text: 'B' }, { key: 'C', text: 'C' }],
      correctAnswerJson: { A: 'a', B: 'b', C: 'c' }, explanation: 'A-a, B-b, C-c.' },
    { exerciseNumber: 2, sortOrder: 1, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Tiếng "học" gồm những phần nào?',
      optionsJson: [{ key: 'A', text: 'Âm đầu h + vần oc + thanh nặng' }, { key: 'B', text: 'Chỉ có vần' }, { key: 'C', text: 'Chỉ có âm đầu' }, { key: 'D', text: 'Không có dấu' }],
      correctAnswerJson: 'A', explanation: '"học" = h + oc + dấu nặng.' },
    { exerciseNumber: 2, sortOrder: 2, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: 'Sắp xếp thành câu: "Bé đi học"',
      optionsJson: [{ key: '1', text: 'Bé' }, { key: '2', text: 'đi' }, { key: '3', text: 'học' }],
      correctAnswerJson: ['1', '2', '3'], explanation: '"Bé đi học" là câu đúng.' },
    { exerciseNumber: 2, sortOrder: 3, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Từ nào viết đúng chính tả?',
      optionsJson: [{ key: 'A', text: 'học sinh' }, { key: 'B', text: 'hoc sinh' }, { key: 'C', text: 'hộc sinh' }, { key: 'D', text: 'hok sinh' }],
      correctAnswerJson: 'A', explanation: '"học sinh" là cách viết đúng.' },
    { exerciseNumber: 2, sortOrder: 4, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: 'Câu "Em yêu trường em." viết đúng chính tả',
      correctAnswerJson: true, explanation: 'Câu đó viết đúng chính tả.' },
    { exerciseNumber: 2, sortOrder: 5, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Từ nào đồng nghĩa với "vui vẻ"?',
      optionsJson: [{ key: 'A', text: 'hạnh phúc' }, { key: 'B', text: 'buồn' }, { key: 'C', text: 'lo lắng' }, { key: 'D', text: 'mệt mỏi' }],
      correctAnswerJson: 'A', explanation: '"Hạnh phúc" đồng nghĩa với "vui vẻ".' },
    { exerciseNumber: 2, sortOrder: 6, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Câu nào là câu hỏi?',
      optionsJson: [{ key: 'A', text: 'Em tên là gì?' }, { key: 'B', text: 'Em đi học.' }, { key: 'C', text: 'Bé ngủ ngoan.' }, { key: 'D', text: 'Mẹ về rồi.' }],
      correctAnswerJson: 'A', explanation: '"Em tên là gì?" là câu hỏi vì có dấu chấm hỏi.' },
    { exerciseNumber: 2, sortOrder: 7, difficultyLevel: 'medium', questionType: 'matching',
      questionText: 'Nối từ với loại từ',
      optionsJson: [{ key: 'A', text: 'bàn' }, { key: 'B', text: 'chạy' }, { key: 'C', text: 'đẹp' }],
      correctAnswerJson: { A: 'danh từ', B: 'động từ', C: 'tính từ' }, explanation: 'bàn-danh từ, chạy-động từ, đẹp-tính từ.' },
    { exerciseNumber: 2, sortOrder: 8, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Dấu thanh nào tạo tiếng có âm điệu cao nhất?',
      optionsJson: [{ key: 'A', text: 'Dấu sắc (/)' }, { key: 'B', text: 'Dấu huyền (\\)' }, { key: 'C', text: 'Dấu nặng (.)' }, { key: 'D', text: 'Thanh ngang' }],
      correctAnswerJson: 'A', explanation: 'Dấu sắc tạo âm điệu cao trong tiếng Việt.' },
    { exerciseNumber: 2, sortOrder: 9, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: 'Sắp xếp thành câu: "Mẹ mua hoa về nhà"',
      optionsJson: [{ key: '1', text: 'Mẹ' }, { key: '2', text: 'mua' }, { key: '3', text: 'hoa' }, { key: '4', text: 'về' }, { key: '5', text: 'nhà' }],
      correctAnswerJson: ['1', '2', '3', '4', '5'], explanation: '"Mẹ mua hoa về nhà" là câu đúng.' },
    { exerciseNumber: 2, sortOrder: 10, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: 'Câu "Bé" là một câu hoàn chỉnh',
      correctAnswerJson: false, explanation: '"Bé" chỉ là một từ, chưa đủ chủ ngữ và vị ngữ.' },
    { exerciseNumber: 3, sortOrder: 1, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Câu nào dùng đúng dấu câu?',
      optionsJson: [{ key: 'A', text: 'Em đi học.' }, { key: 'B', text: 'Em đi học,' }, { key: 'C', text: 'Em đi học!' }, { key: 'D', text: 'Em đi học?' }],
      correctAnswerJson: 'A', explanation: 'Câu kể kết thúc bằng dấu chấm.' },
    { exerciseNumber: 3, sortOrder: 2, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Từ nào trái nghĩa với "vui"?',
      optionsJson: [{ key: 'A', text: 'buồn' }, { key: 'B', text: 'hạnh phúc' }, { key: 'C', text: 'sung sướng' }, { key: 'D', text: 'vui vẻ' }],
      correctAnswerJson: 'A', explanation: '"Buồn" là trái nghĩa với "vui".' },
    { exerciseNumber: 3, sortOrder: 3, difficultyLevel: 'hard', questionType: 'matching',
      questionText: 'Nối từ với trái nghĩa',
      optionsJson: [{ key: 'A', text: 'to' }, { key: 'B', text: 'cao' }, { key: 'C', text: 'nhanh' }],
      correctAnswerJson: { A: 'nhỏ', B: 'thấp', C: 'chậm' }, explanation: 'to-nhỏ, cao-thấp, nhanh-chậm.' },
    { exerciseNumber: 3, sortOrder: 4, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Câu nào diễn đạt đúng ý nghĩa?',
      optionsJson: [{ key: 'A', text: 'Mặt trời mọc ở hướng Đông.' }, { key: 'B', text: 'Mặt trời mọc ở hướng Tây.' }, { key: 'C', text: 'Mặt trời lặn ở hướng Đông.' }, { key: 'D', text: 'Mặt trời đứng yên.' }],
      correctAnswerJson: 'A', explanation: 'Mặt trời mọc ở hướng Đông là đúng.' },
    { exerciseNumber: 3, sortOrder: 5, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: 'Câu "Em học bài" có 3 tiếng',
      correctAnswerJson: true, explanation: '"Em học bài" có đúng 3 tiếng: Em, học, bài.' },
    { exerciseNumber: 3, sortOrder: 6, difficultyLevel: 'hard', questionType: 'drag_drop',
      questionText: 'Sắp xếp câu: "Chúng em yêu trường lớp"',
      optionsJson: [{ key: '1', text: 'Chúng' }, { key: '2', text: 'em' }, { key: '3', text: 'yêu' }, { key: '4', text: 'trường' }, { key: '5', text: 'lớp' }],
      correctAnswerJson: ['1', '2', '3', '4', '5'], explanation: '"Chúng em yêu trường lớp" là câu đúng.' },
    { exerciseNumber: 3, sortOrder: 7, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Câu "Bé học bài chăm chỉ" có bao nhiêu từ?',
      optionsJson: [{ key: 'A', text: '4' }, { key: 'B', text: '5' }, { key: 'C', text: '3' }, { key: 'D', text: '6' }],
      correctAnswerJson: 'A', explanation: '"Bé / học bài / chăm chỉ" có thể tính là 4 từ.' },
    { exerciseNumber: 3, sortOrder: 8, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Tìm câu sai chính tả',
      optionsJson: [{ key: 'A', text: 'Em hoc bài.' }, { key: 'B', text: 'Em học bài.' }, { key: 'C', text: 'Bé đi học.' }, { key: 'D', text: 'Mẹ nấu cơm.' }],
      correctAnswerJson: 'A', explanation: '"hoc" sai chính tả, phải là "học".' },
    { exerciseNumber: 3, sortOrder: 9, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: 'Tiếng Việt viết từ trái sang phải',
      correctAnswerJson: true, explanation: 'Tiếng Việt viết theo chiều từ trái sang phải.' },
    { exerciseNumber: 3, sortOrder: 10, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Câu nào dùng đúng dấu phẩy?',
      optionsJson: [{ key: 'A', text: 'Em học bài, còn mẹ nấu cơm.' }, { key: 'B', text: 'Em học bài còn mẹ nấu cơm.' }, { key: 'C', text: 'Em học bài. còn mẹ nấu cơm.' }, { key: 'D', text: 'Em học bài! còn mẹ nấu cơm.' }],
      correctAnswerJson: 'A', explanation: 'Dấu phẩy dùng để ngăn cách các vế câu.' },
  ];
}

function makeDocHieuQuizzes(l: DocHieuLesson): QuizSeed[] {
  const story = l.story;
  const topic = l.topic;
  return [
    // Bài tập 1: Đọc hiểu nội dung (easy)
    { exerciseNumber: 1, sortOrder: 1, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Câu chuyện "${story}" nói về chủ đề gì?`,
      optionsJson: [{ key: 'A', text: topic }, { key: 'B', text: 'Khoa học' }, { key: 'C', text: 'Toán học' }, { key: 'D', text: 'Mỹ thuật' }],
      correctAnswerJson: 'A', explanation: `Câu chuyện "${story}" nói về chủ đề ${topic}.` },
    { exerciseNumber: 1, sortOrder: 2, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Câu chuyện "${story}" là một bài đọc hiểu`,
      correctAnswerJson: true, explanation: 'Đây là bài đọc hiểu trong chương trình Tiếng Việt lớp 1.' },
    { exerciseNumber: 1, sortOrder: 3, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Câu chuyện "${story}" thuộc thể loại nào?`,
      optionsJson: [{ key: 'A', text: 'Truyện đọc' }, { key: 'B', text: 'Thơ' }, { key: 'C', text: 'Bảng số' }, { key: 'D', text: 'Bản đồ' }],
      correctAnswerJson: 'A', explanation: `"${story}" là truyện đọc trong sách giáo khoa.` },
    { exerciseNumber: 1, sortOrder: 4, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Đọc bài "${story}" giúp em hiểu thêm về ${topic}`,
      correctAnswerJson: true, explanation: `Đúng, bài giúp hiểu hơn về ${topic}.` },
    { exerciseNumber: 1, sortOrder: 5, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: 'Khi đọc bài, em cần chú ý điều gì?',
      optionsJson: [{ key: 'A', text: 'Đọc rõ ràng, hiểu nghĩa từng câu' }, { key: 'B', text: 'Đọc thật nhanh' }, { key: 'C', text: 'Đọc thầm không hiểu cũng được' }, { key: 'D', text: 'Không cần đọc' }],
      correctAnswerJson: 'A', explanation: 'Đọc rõ ràng và hiểu nghĩa từng câu là quan trọng nhất.' },
    { exerciseNumber: 1, sortOrder: 6, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: `Chủ đề "${topic}" trong cuộc sống hằng ngày là gì?`,
      optionsJson: [{ key: 'A', text: `Những điều liên quan đến ${topic}` }, { key: 'B', text: 'Môn toán' }, { key: 'C', text: 'Môn nhạc' }, { key: 'D', text: 'Môn thể dục' }],
      correctAnswerJson: 'A', explanation: `${topic} là chủ đề về cuộc sống thực tế.` },
    { exerciseNumber: 1, sortOrder: 7, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: 'Tiêu đề của câu chuyện thường nói lên nội dung chính',
      correctAnswerJson: true, explanation: 'Tiêu đề giúp người đọc biết nội dung chính của câu chuyện.' },
    { exerciseNumber: 1, sortOrder: 8, difficultyLevel: 'easy', questionType: 'single_choice',
      questionText: 'Đọc hiểu nghĩa là gì?',
      optionsJson: [{ key: 'A', text: 'Hiểu được nội dung và ý nghĩa của bài' }, { key: 'B', text: 'Đọc thật to' }, { key: 'C', text: 'Đọc xong là xong' }, { key: 'D', text: 'Không cần hiểu' }],
      correctAnswerJson: 'A', explanation: 'Đọc hiểu nghĩa là nắm được nội dung và ý nghĩa bài đọc.' },
    { exerciseNumber: 1, sortOrder: 9, difficultyLevel: 'easy', questionType: 'true_false',
      questionText: `Câu chuyện "${story}" có thể dạy cho em bài học về ${topic}`,
      correctAnswerJson: true, explanation: `Các câu chuyện trong sách đều mang ý nghĩa giáo dục.` },
    { exerciseNumber: 1, sortOrder: 10, difficultyLevel: 'easy', questionType: 'matching',
      questionText: 'Nối câu hỏi với loại câu hỏi',
      optionsJson: [{ key: 'A', text: 'Ai?' }, { key: 'B', text: 'Ở đâu?' }, { key: 'C', text: 'Khi nào?' }],
      correctAnswerJson: { A: 'Hỏi về người', B: 'Hỏi về nơi chốn', C: 'Hỏi về thời gian' },
      explanation: 'Ai-người, Ở đâu-nơi chốn, Khi nào-thời gian.' },
    // Bài tập 2: Từ ngữ và ngữ pháp (medium)
    { exerciseNumber: 2, sortOrder: 1, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Từ nào liên quan đến chủ đề "${topic}"?`,
      optionsJson: [
        { key: 'A', text: topic === 'gia đình' ? 'bố mẹ' : topic === 'trường học' ? 'lớp học' : topic === 'thiên nhiên' ? 'cây cối' : topic === 'đạo đức' ? 'trung thực' : 'cuộc sống' },
        { key: 'B', text: 'phép tính' }, { key: 'C', text: 'hình học' }, { key: 'D', text: 'nhạc cụ' }
      ],
      correctAnswerJson: 'A', explanation: `Từ đó liên quan đến chủ đề ${topic}.` },
    { exerciseNumber: 2, sortOrder: 2, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: `Sắp xếp thành câu có nghĩa về "${story}"`,
      optionsJson: [{ key: '1', text: 'Em' }, { key: '2', text: 'đọc' }, { key: '3', text: 'bài' }, { key: '4', text: 'chăm chỉ' }],
      correctAnswerJson: ['1', '2', '3', '4'], explanation: '"Em đọc bài chăm chỉ." là câu đúng.' },
    { exerciseNumber: 2, sortOrder: 3, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Câu "Em rất yêu gia đình." có bao nhiêu từ?',
      optionsJson: [{ key: 'A', text: '4' }, { key: 'B', text: '3' }, { key: 'C', text: '5' }, { key: 'D', text: '6' }],
      correctAnswerJson: 'A', explanation: '"Em / rất / yêu / gia đình" có 4 từ.' },
    { exerciseNumber: 2, sortOrder: 4, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: `Chủ đề ${topic} xuất hiện nhiều trong cuộc sống hằng ngày của em`,
      correctAnswerJson: true, explanation: `${topic} là chủ đề gần gũi với học sinh lớp 1.` },
    { exerciseNumber: 2, sortOrder: 5, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Từ nào là tính từ?',
      optionsJson: [{ key: 'A', text: 'xinh đẹp' }, { key: 'B', text: 'học sinh' }, { key: 'C', text: 'chạy nhảy' }, { key: 'D', text: 'bàn ghế' }],
      correctAnswerJson: 'A', explanation: '"Xinh đẹp" là tính từ chỉ đặc điểm.' },
    { exerciseNumber: 2, sortOrder: 6, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: `Câu chuyện "${story}" kết thúc như thế nào?`,
      optionsJson: [{ key: 'A', text: 'Có ý nghĩa và bài học tốt' }, { key: 'B', text: 'Không có kết thúc' }, { key: 'C', text: 'Buồn và không giải quyết được' }, { key: 'D', text: 'Không rõ ràng' }],
      correctAnswerJson: 'A', explanation: 'Các câu chuyện trong SGK đều có kết thúc có ý nghĩa.' },
    { exerciseNumber: 2, sortOrder: 7, difficultyLevel: 'medium', questionType: 'matching',
      questionText: 'Nối từ với nghĩa',
      optionsJson: [{ key: 'A', text: 'vui vẻ' }, { key: 'B', text: 'chăm chỉ' }, { key: 'C', text: 'trung thực' }],
      correctAnswerJson: { A: 'luôn vui cười', B: 'làm việc siêng năng', C: 'nói thật, không dối trá' },
      explanation: 'vui vẻ, chăm chỉ, trung thực là các phẩm chất tốt.' },
    { exerciseNumber: 2, sortOrder: 8, difficultyLevel: 'medium', questionType: 'single_choice',
      questionText: 'Từ nào là động từ?',
      optionsJson: [{ key: 'A', text: 'học' }, { key: 'B', text: 'trường' }, { key: 'C', text: 'vui' }, { key: 'D', text: 'sách' }],
      correctAnswerJson: 'A', explanation: '"Học" là động từ chỉ hành động.' },
    { exerciseNumber: 2, sortOrder: 9, difficultyLevel: 'medium', questionType: 'drag_drop',
      questionText: 'Sắp xếp: "Bài học hay và bổ ích"',
      optionsJson: [{ key: '1', text: 'Bài' }, { key: '2', text: 'học' }, { key: '3', text: 'hay' }, { key: '4', text: 'và' }, { key: '5', text: 'bổ ích' }],
      correctAnswerJson: ['1', '2', '3', '4', '5'], explanation: '"Bài học hay và bổ ích" là cụm từ đúng.' },
    { exerciseNumber: 2, sortOrder: 10, difficultyLevel: 'medium', questionType: 'true_false',
      questionText: `Câu chuyện về "${topic}" giúp em học được bài học đạo đức`,
      correctAnswerJson: true, explanation: 'Các câu chuyện trong SGK đều mang ý nghĩa giáo dục.' },
    // Bài tập 3: Vận dụng và suy luận (hard)
    { exerciseNumber: 3, sortOrder: 1, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Bài học quan trọng nhất từ câu chuyện "${story}" là gì?`,
      optionsJson: [
        { key: 'A', text: topic === 'đạo đức' ? 'Sống trung thực và tốt bụng' : topic === 'gia đình' ? 'Yêu thương gia đình' : topic === 'trường học' ? 'Chăm chỉ học tập' : `Trân trọng ${topic}` },
        { key: 'B', text: 'Không cần học bài' }, { key: 'C', text: 'Chỉ chơi thôi' }, { key: 'D', text: 'Không có bài học' }
      ],
      correctAnswerJson: 'A', explanation: `Câu chuyện "${story}" dạy chúng ta về ${topic}.` },
    { exerciseNumber: 3, sortOrder: 2, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Nếu em là nhân vật trong câu chuyện, em sẽ làm gì?',
      optionsJson: [{ key: 'A', text: 'Làm điều đúng và tốt' }, { key: 'B', text: 'Không quan tâm' }, { key: 'C', text: 'Làm điều xấu' }, { key: 'D', text: 'Bỏ đi chỗ khác' }],
      correctAnswerJson: 'A', explanation: 'Chúng ta nên làm điều đúng và tốt như bài học trong câu chuyện.' },
    { exerciseNumber: 3, sortOrder: 3, difficultyLevel: 'hard', questionType: 'matching',
      questionText: 'Nối hành động với đánh giá',
      optionsJson: [{ key: 'A', text: 'Giúp đỡ bạn' }, { key: 'B', text: 'Nói dối' }, { key: 'C', text: 'Học chăm chỉ' }],
      correctAnswerJson: { A: 'Tốt, đáng khen', B: 'Không tốt, cần sửa', C: 'Tốt, đáng khen' },
      explanation: 'Giúp bạn và học chăm chỉ là tốt; nói dối là không tốt.' },
    { exerciseNumber: 3, sortOrder: 4, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Câu chuyện "${story}" liên quan đến em như thế nào?`,
      optionsJson: [{ key: 'A', text: `Giúp em hiểu hơn về ${topic} trong cuộc sống` }, { key: 'B', text: 'Không liên quan gì' }, { key: 'C', text: 'Chỉ dành cho người lớn' }, { key: 'D', text: 'Không có ích' }],
      correctAnswerJson: 'A', explanation: `Câu chuyện giúp em hiểu về ${topic}.` },
    { exerciseNumber: 3, sortOrder: 5, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: 'Đọc nhiều sách giúp tăng vốn từ và hiểu biết',
      correctAnswerJson: true, explanation: 'Đọc sách thường xuyên giúp mở rộng kiến thức và từ vựng.' },
    { exerciseNumber: 3, sortOrder: 6, difficultyLevel: 'hard', questionType: 'drag_drop',
      questionText: 'Sắp xếp thành câu hoàn chỉnh',
      optionsJson: [{ key: '1', text: 'Em' }, { key: '2', text: 'rất' }, { key: '3', text: 'thích' }, { key: '4', text: 'đọc' }, { key: '5', text: 'sách' }],
      correctAnswerJson: ['1', '2', '3', '4', '5'], explanation: '"Em rất thích đọc sách." là câu hoàn chỉnh.' },
    { exerciseNumber: 3, sortOrder: 7, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: `Em học được gì từ chủ đề "${topic}"?`,
      optionsJson: [
        { key: 'A', text: `Hiểu biết và yêu quý ${topic}` },
        { key: 'B', text: 'Không học được gì' }, { key: 'C', text: 'Chỉ học từ mới' }, { key: 'D', text: 'Không quan trọng' }
      ],
      correctAnswerJson: 'A', explanation: `Chủ đề ${topic} giúp em hiểu biết thêm về cuộc sống.` },
    { exerciseNumber: 3, sortOrder: 8, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Câu nào thể hiện em đã hiểu bài?',
      optionsJson: [{ key: 'A', text: 'Em có thể kể lại câu chuyện cho bạn nghe' }, { key: 'B', text: 'Em đọc xong là quên ngay' }, { key: 'C', text: 'Em không hiểu gì' }, { key: 'D', text: 'Em không quan tâm' }],
      correctAnswerJson: 'A', explanation: 'Kể lại được câu chuyện nghĩa là đã hiểu bài.' },
    { exerciseNumber: 3, sortOrder: 9, difficultyLevel: 'hard', questionType: 'true_false',
      questionText: `Câu chuyện "${story}" phù hợp với học sinh lớp 1`,
      correctAnswerJson: true, explanation: 'Đây là bài đọc trong sách giáo khoa lớp 1, phù hợp với lứa tuổi.' },
    { exerciseNumber: 3, sortOrder: 10, difficultyLevel: 'hard', questionType: 'single_choice',
      questionText: 'Sau khi đọc câu chuyện, em nên làm gì?',
      optionsJson: [{ key: 'A', text: 'Suy nghĩ về bài học và áp dụng vào cuộc sống' }, { key: 'B', text: 'Bỏ qua và không nghĩ đến' }, { key: 'C', text: 'Chỉ nhớ tên câu chuyện' }, { key: 'D', text: 'Không cần làm gì' }],
      correctAnswerJson: 'A', explanation: 'Áp dụng bài học vào cuộc sống là cách học hiệu quả nhất.' },
  ];
}

function generateQuizzes(lesson: LessonData): QuizSeed[] {
  switch (lesson.type) {
    case 'chu-cai': return makeChuCaiQuizzes(lesson);
    case 'van': return makeVanQuizzes(lesson);
    case 'on-tap': return makeOnTapQuizzes(lesson);
    case 'doc-hieu': return makeDocHieuQuizzes(lesson);
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  await ds.initialize();
  console.log('✅ DB connected');

  let totalInserted = 0;

  for (const lesson of LESSONS) {
    await ds.query('DELETE FROM quizzes WHERE lessonId = ?', [lesson.id]);
    const quizzes = generateQuizzes(lesson);
    for (const q of quizzes) {
      await ds.query(
        `INSERT INTO quizzes
          (questionText, questionType, difficultyLevel, exerciseNumber, sortOrder,
           optionsJson, correctAnswerJson, explanation, lessonId, isActive, points, createdAt, updatedAt)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 10, NOW(), NOW())`,
        [
          q.questionText, q.questionType, q.difficultyLevel,
          q.exerciseNumber, q.sortOrder,
          q.optionsJson ? JSON.stringify(q.optionsJson) : null,
          JSON.stringify(q.correctAnswerJson),
          q.explanation ?? null,
          lesson.id,
        ],
      );
    }
    console.log(`✅ Lesson ${lesson.id}: ${quizzes.length} câu hỏi`);
    totalInserted += quizzes.length;
  }

  console.log(`\n🎉 Tổng cộng: ${totalInserted} câu hỏi cho ${LESSONS.length} bài học`);
  await ds.destroy();
}

main().catch((e) => { console.error(e); process.exit(1); });
